### ISSUE TITLE
非常好用的一个导航栏，貌似不能使用cocoapods下载

### ISSUE THREAD

**Issue by heyehao2008** [rickytan/RTRootNavigationController#1]
持续关注此库，在正式项目中试用

**Comment by rickytan** [comment]
我自己也在正在正式项目中使用，可以下载，最新版 0.5.8。有 bug 会及时修复

![2016-06-14 12 54 23](https://cloud.githubusercontent.com/assets/1250207/16031565/2943b7d8-322f-11e6-907f-55074a144310.png)

**Comment by heyehao2008** [comment]
我的cocoapods还是不能下载，找不到这个库，终端搜索也搜不到，搜AFNetworking是正常的，搜索应该没问题。你demo中的cocoapod貌似是直接从本地路径加载的
<img width="569" alt="ronda -bash 80x24 at 2 04 40" src="https://cloud.githubusercontent.com/assets/7590049/16032526/036af116-3239-11e6-807a-232cbf6cde83.png">

**Comment by heyehao2008** [comment]
OK,现在可以了，终端可以搜索到了
有个问题，怎么控制不旋转呢？我现在是新建一个类继承这个navigation，重写了
`- (BOOL)shouldAutorotate{`
   ` return NO;//不支持旋转`
`}`
这样才能控制旋转。但是我的UIViewController里面是重写了不支持旋转的
继承于UINavigationController的子类重写
`- (BOOL)shouldAutorotate{`
  `  return self.topViewController.shouldAutorotate;`
`}`
就可以在导航栏控制的每个UIViewController里面控制旋转，但是使用这个库貌似不行

**Comment by rickytan** [comment]
![2016-06-14 4 56 18](https://cloud.githubusercontent.com/assets/1250207/16036978/f019f838-3250-11e6-9bc6-8d1795252bfb.png)
下面两个勾去掉就好了

**Comment by rickytan** [comment]
这是个问题
