### ISSUE TITLE
在根控制器使用UISearchBar 出现问题

### ISSUE THREAD

**Issue by teng555teng** [rickytan/RTRootNavigationController#10]
![qq 20160630203409](https://cloud.githubusercontent.com/assets/4971709/16641543/58e5ce7e-4434-11e6-83e5-a67e504aaf24.png)

状态栏 透明了 并且滚动能看到 tableview的信息
暂时没想到解决办法

**Comment by rickytan** [comment]
这是个问题

**Comment by rickytan** [comment]
![2016-07-07 2 25 52](https://cloud.githubusercontent.com/assets/1250207/16644325/bceaf6f0-444e-11e6-9572-11cdf2ead495.png)
无法重现这个问题，请问你的 searchbar 是怎么加上去的？

**Comment by rickytan** [comment]
帮忙测试下这个分支：https://github.com/rickytan/RTRootNavigationController/tree/issue10 有没有解决问题？

**Comment by teng555teng** [comment]
[self.tableView setTableHeaderView:self.searchBar];  搭配 UISearchDisplayController

**Comment by teng555teng** [comment]
我是纯代码写的 并不会 走 https://github.com/rickytan/RTRootNavigationController/tree/issue10

**Comment by teng555teng** [comment]
###不只是在根控制器 所有的控制器都会出现这个不过

**Comment by teng555teng** [comment]
self.edgesForExtendedLayout = UIRectEdgeNone;  问题解决 ^=^
