### ISSUE TITLE
手势滑动POP页面 无效，请帮忙确认。谢谢哈

### ISSUE THREAD

**Issue by llywuchen** [rickytan/RTRootNavigationController#102]
-(BOOL)rt_hasSetInteractivePop { 
    return !!objc_getAssociatedObject(self, @selector(rt_disableInteractivePop)); 
}
这里是不是多了一个！，应该是bug。

**Comment by rickytan** [comment]
两个 ! 只是将 一个值转为 布尔值，不是 bug。
你是不是有自定义  leftBarButtonItem ？0.6 以上版当有自定义  left item 时默认禁用了手势返回，change log 中有说明，与系统导航器行为一致

**Comment by llywuchen** [comment]
一个变量是是否disable 手势pop,另一个变量是否设置了手势POP，这两个变量可以相等吗？是不是应该取反呢？

**Comment by rickytan** [comment]
没有设置值是 nil，不禁用是 `[NSNumber numberWithBool:NO]` ，这两个还是不一样的。做这个判断是为了不影响使用者的设置，如果使用者没有设置，那么本项目自动设置一个

**Comment by llywuchen** [comment]
如果t_disableInteractivePop 不为nil的时候，rt_hasSetInteractivePop的值为 ！！（！nil），也就是true,是这样的吗

**Comment by rickytan** [comment]
是的。简单中文理解就是，`rt_disableInteractivePop` 不为 nil，即说明有人设置过它的值，所以 has set 为 true

**Comment by xuxi1995** [comment]
需要在继承导航控制器设置rt_disableInteractivePop = NO,感觉有点麻烦, 新版本有这个问题 ,我还以为怎么了,还有更好的解决方案吗,全局支持全屏

**Comment by rickytan** [comment]
@xuxi1995 不设置 leftBarButtonItem，不隐藏导航条就好

**Comment by xuxi1995** [comment]
但是需要很多种返回图片的样式,所以....

**Comment by wcb133** [comment]
如果是重写 - rt_customBackItemWithTarget:action: 的话是侧滑可以的，但是在同一个VC需要根据不同的操作来变换leftBarButtonItem的话，这个这样设计就不好了

**Comment by rickytan** [comment]
这种情况你可以自己设置 `leftItem`，同时设置 `self.rt_disableInteractivePop = NO` 就好

**Comment by wcb133** [comment]
看了一下代码，按照里面的代码逻辑，rt_disableInteractivePop = NO这个设置必须在push进导航栏之前设置，如果是在控制器的viewDidload里面设置，是没用的

**Comment by rickytan** [comment]
之前设置或 did load 都是可以的，did appear 之后改是无效的

**Comment by wcb133** [comment]
确实是可以的
