### ISSUE TITLE
pop多级VC无效

### ISSUE THREAD

**Issue by laoSanDr** [rickytan/RTRootNavigationController#106]
[self.rt_navigationController popToViewController:nvc animated:YES complete:nil];
这样跳转无效，请问怎么解决。有遇到这个问题的吗？

**Comment by rickytan** [comment]
这样就好了，去掉 `rt_`
```objective-c
[self.navigationController popToViewController:nvc animated:YES complete:nil];
```

**Comment by rickytan** [comment]
你的 **nvc** 怎么拿到的？

**Comment by laoSanDr** [comment]
[[ViewController alloc] init]  拿到的。刚才试了去掉 rt_  还是不行。

**Comment by rickytan** [comment]
呃。。。
pop 只能到已经在 navigation 中的，不能生成新的。你需要再好好理解下 navigation

**Comment by laoSanDr** [comment]
我要怎么能拿到 之前的VC？  我用self.navigationController.viewControllers 拿到的只有一个。

**Comment by rickytan** [comment]
`0.6.3` 之前的版本需要 `self.rt_navigationController.rt_viewControllers`，`0.6.3` 版可以直接 `self.navigationController.viewControllers` 拿到了
