### ISSUE TITLE
导航栏隐藏问题

### ISSUE THREAD

**Issue by lotus-lotus** [rickytan/RTRootNavigationController#108]
隐藏导航栏但是不需要隐藏title和backItem....
[self.navigationController.navigationBar setBackgroundImage:[UIImage new] forBarMetrics:UIBarMetricsDefault];
    [self.navigationController.navigationBar setShadowImage:[UIImage new]];
会影响交互,有什么解决

**Comment by rickytan** [comment]
影响什么交互？手势返回？

**Comment by xuxi1995** [comment]
[self.navigationController.navigationBar setBackgroundImage：[UIImage new] forBarMetrics：UIBarMetricsDefault]; 
[self.navigationController.navigationBar setShadowImage：[UIImage的新]]; 使用这个隐藏  下拉刷新的有顶部64(导航栏)位置 不能交互

**Comment by rickytan** [comment]
一般没人从那么顶上拖动操作吧？一定要的话，试试自定义 UINavigationBar，重写 hitTest 方法，返回 nil
