### ISSUE TITLE
请问自定义返回按钮后，如果修正按钮的偏移？

### ISSUE THREAD

**Issue by KarinoSharuru** [rickytan/RTRootNavigationController#113]
系统导航栏的话，可以通过UIBarButtonSystemItemFixedSpace，返回一个UIBarButtonItem数组。
但UIViewController + RTRootNavigationController分类中似乎只有返回单个UIBarButtonItem的方法
`(UIBarButtonItem *)rt_customBackItemWithTarget:(id)target action:(SEL)action;`
倘若直接使用系统的`self.navigationItem.leftBarButtonItems = @[space, returnBtn]`的话，原本默认启用的边缘返回手势就失效了。

**Comment by KarinoSharuru** [comment]
我发现在VC中主动设置`self.rt_disableInteractivePop = NO`后，上述情况下失效的边缘返回手势恢复了。唔....但总感觉是绕了圈圈。

**Comment by rickytan** [comment]
手动设置 leftItem 后手势返回将失效，[changelog.md](https://github.com/rickytan/RTRootNavigationController/blob/master/CHANGELOG.md) 中也说明了
