### ISSUE TITLE
RTRootNavigationController会跟CYLTabBarController造成冲突吗？

### ISSUE THREAD

**Issue by loveJuly** [rickytan/RTRootNavigationController#116]
两者使用的时候都需要设置为window的根控制器。。
希望大神给个正确姿势

**Comment by rickytan** [comment]
运行下 Example 程序，在 `appDelegate` 中有两种集成方式，一种是 push 后隐藏 tabBar，一种是 push 后不隐藏 tabBar ，看你自己需求

**Comment by loveJuly** [comment]
已解决，谢谢
