### ISSUE TITLE
更新库后，导致popToViewController:animated:有问题

### ISSUE THREAD

**Issue by MIssxixi** [rickytan/RTRootNavigationController#117]
采用https://github.com/rickytan/RTRootNavigationController/blob/master/Example/RTRootNavigationController/RTAppDelegate.m#L25-L29
隐藏tabBar，然后在某个一级tab的aVC -> bVC，并将aVC作为属性传递给bVC,则[bVC popToViewController:aVC animated:YES]失效. 见附近demo
[RTTest.zip](https://github.com/rickytan/RTRootNavigationController/files/1305500/RTTest.zip)

**Comment by rickytan** [comment]
你这个层级是不对的。
```
RootNavigationController
`- TabBarController
|    ` - ViewController
`- TestViewController
```

发现了吗？你的 TestViewController 指向的 ViewController 不是跟它一级的，而是 TabBar 的子级。换句话说，  ViewController 根本不在   Navigation   的栈中

解决方法：
1. 直接 popToRoot
2. 传 TabBar 传  Test
