### ISSUE TITLE
RTRootNavigationController怎么隐藏首页导航栏？

### ISSUE THREAD

**Issue by loveJuly** [rickytan/RTRootNavigationController#118]
```objective-c
- (void)navigationController:(UINavigationController*)navigationController willShowViewController:(UIViewController*)viewController animated:(BOOL)animated{
    if([[viewController class] isSubclassOfClass:[self class]]) {
        [self.navigationController setNavigationBarHidden:YES animated:YES];
    }
    
    // ----- 删除代理，防止该controller销毁后引起navigationController.delegate指向野指针造成崩溃
    if(![[viewController class] isSubclassOfClass:[self class]]) {
        [self.navigationController setNavigationBarHidden:NO animated:YES];
        self.navigationController.delegate = nil;
    }
}
```
这是使用系统的nav的时候隐藏首页导航栏的操作，设置了RTRootNavigationController之后这个就不起作用了，请问RTRootNavigationController隐藏首页导航栏应该怎么操作？

**Comment by rickytan** [comment]
在首页的 vc viewDidLoad 设置 `self.navigationController.navigationBarHidden = YES` 就好

**Comment by rickytan** [comment]
除非你很清楚在做什么，不要轻易改这个 delegate  方法

**Comment by loveJuly** [comment]
我用RTRootNavigationController去设置了根控制器，那么self.navigationController的类为什么还是UINavigationController？
还有一个问题：RTRootNavigationController跟一些导航栏的第三方（比如：WRNavigationBar）一起使用好像会有冲突。

**Comment by rickytan** [comment]
`WRNavigationBar` 库的功能用 appearance 都可以实现，我找不到什么用的必要

**Comment by rickytan** [comment]
你的 `self` 是怎么加到 navigation 栈中的？

**Comment by loveJuly** [comment]
参照了你demo里面的方式：
SDHomeViewController *firstViewController = [[SDHomeViewController alloc] init];
    UIViewController *firstNavigationController = [[CYLBaseNavigationController alloc]
                                                   initWithRootViewController:firstViewController];
    
    SDNewsTableViewController *secondViewController = [[SDNewsTableViewController alloc] init];
    UIViewController *secondNavigationController = [[CYLBaseNavigationController alloc]
                                                    initWithRootViewController:secondViewController];
    
    PersonalCenterTableViewController *thirdViewController = [[PersonalCenterTableViewController alloc] init];
    UIViewController *thirdNavigationController = [[CYLBaseNavigationController alloc]
                                                   initWithRootViewController:thirdViewController];
设置tabBarController的时候设置的。

**Comment by rickytan** [comment]
你用的其他项目的 navigation ，这个我也管不了啊

**Comment by loveJuly** [comment]
抱歉现在才看到，这个类是继承自RTRootNavigationController的：
@interface CYLBaseNavigationController : RTRootNavigationController
@end

@implementation CYLBaseNavigationController

- (void)pushViewController:(UIViewController *)viewController animated:(BOOL)animated complete:(void (^)(BOOL))block{
    if (self.viewControllers.count > 0) {
        viewController.hidesBottomBarWhenPushed = YES;
    }
    
    [super pushViewController:viewController animated:animated complete:nil];
}
不确定是不是写法的问题？

**Comment by rickytan** [comment]
麻烦先把代码用  ```     ``` 包一下哈。
这个写法是没必要的，demo 中两种方式，有一种可以做到 push 后隐藏  tabBar ，不需要再单独 hidesBottomBarWhenPushed。
另外，有个问题是  complete  block 参数没有传到 super，虽然影响不大

**Comment by loveJuly** [comment]
好的，我再去修改一下代码。

**Comment by rickytan** [comment]
我猜你现在的需求是， 主界面是 tab ，然后 tab 下的  vc0  vc1  vc2 没有 nav ，但是点了 vc0 下的按钮后  push  到  vc3 ，有 nav，没有 tab ，对吗？

**Comment by loveJuly** [comment]
恩恩，push到vc3之后的控制器自主确定导航栏的样式、是否隐藏。

**Comment by rickytan** [comment]
你可以这样吧：
```objective-c
    UITabBarController *tabBar = [[UITabBarController alloc] init];

    ViewController *vc0 = 
    ViewController *vc1 = 
    ViewController *vc2 = 

    tabBar.viewControllers = @[vc0, vc1, vc2];

    self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
    self.window.rootViewController = [[RTRootNavigationController alloc] initWithRootViewControllerNoWrapping:tabBar];
    [self.window makeKeyAndVisible];
```

**Comment by rickytan** [comment]
![simulator screen shot 2017 9 16 5 36 17](https://user-images.githubusercontent.com/1250207/30511151-836bdd18-9b05-11e7-91dd-1475cb1d10ad.png)

**Comment by loveJuly** [comment]
这样写的话，首页的导航栏非全部隐藏也可以手动设置么？
Task <0A0815E8-BFD9-41AF-A0B6-95BFFB99A53A>.<30> finished with error - code: -1008
Task <66984596-4C98-4A6D-BD74-CC29AF113E90>.<31> finished with error - code: -1008
Task <C1648058-F133-4130-8CBB-4A135A29A6AC>.<32> finished with error - code: -1008
Task <02C8F5E0-9D41-484C-A70D-0FC1879A49D2>.<33> finished with error - code: -1008
Task <B8F4ACEA-73E5-4D59-977F-74B3EDC0097B>.<34> finished with error - code: -1008

切换tabbar的时候报的一些奇怪东西。

**Comment by rickytan** [comment]
可以的，不隐藏 nav 的 vc 外包一层  RTContainerNavigationController 就行

**Comment by loveJuly** [comment]
楼主，首页控制器设置了RTContainerNavigationController，tableview的wrapperview会下面一个状态栏的高度，设置了：
self.automaticallyAdjustsScrollViewInsets = NO;
self.edgesForExtendedLayout = UIRectEdgeNone;
都不起作用。

**Comment by loveJuly** [comment]
已解决。
