### ISSUE TITLE
关于StatusBar全屏侧滑 

### ISSUE THREAD

**Issue by lotus-lotus** [rickytan/RTRootNavigationController#119]
关于StatusBar全屏侧滑 
因为前面的界面StatusBar是白色的,后面的界面是黑色的StatusBar,侧滑时会立即调用- (UIStatusBarStyle)preferredStatusBarStyle 方法设置成白色的 ,导致后面的界面还没有完全消失就白色了

我是想让第一个界面全部实现完成才改变成白色>>>>>>
<img width="432" alt="7c500d45-8081-46d0-ac4e-7b906c1d340a" src="https://user-images.githubusercontent.com/24632295/30518681-753e6f46-9bb7-11e7-99cb-65d93db364e8.png">

**Comment by rickytan** [comment]
可以这样啊：
```objective-c
@interface YourVC
{
    statusBarStyle 当前style;
}
@end

@implementation YourVC

- (style)preferedStyle {
    return 当前style;
}
- (void)viewWillAppear {
    当前style = [UIApplication sharedApplication.statusBarStyle;
}

- (void)viewDidAppear {
    当前style=while;
    [self updateStatuBarStyle];
}
@end
```
> P.S. 我感觉我是不是可以开个收费咨询项目 😎

**Comment by lotus-lotus** [comment]
刚入行不久，见谅见谅

**Comment by lotus-lotus** [comment]
使用[[UIApplication sharedApplication] statusBarStyle]并不能获取,在B控制器即将消失的时候[[UIApplication sharedApplication] statusBarStyle]的状态等于A控制器设置的白色

**Comment by rickytan** [comment]
如果不实现 preferStyle 是不是能保留最后一次的 style？如果可以你可以先返回  super.perferStyle 的结果，在 did appear 之后再返回自己的结果

**Comment by jiurong001** [comment]
你好，demo 怎样运行起来呢

**Comment by rickytan** [comment]
先 pod install
