### ISSUE TITLE
使用UINavigationBar appearance无法修改导航栏样式

### ISSUE THREAD

**Issue by songhailiang** [rickytan/RTRootNavigationController#12]
我在AppDelegate里使用UINavigationbar appearance无法修改导航栏的样式：
`
[[UINavigationBar appearance] setBarTintColor:[UIColor colorWithRed:58/255.0 green:58/255.0 blue:58/255.0 alpha:1.0]];
[[UINavigationBar appearance] setTintColor:[UIColor whiteColor]];
[[UINavigationBar appearance] setTitleTextAttributes:[NSDictionary dictionaryWithObjectsAndKeys:
                                                          [UIColor whiteColor],NSForegroundColorAttributeName
                                                          ,[UIFont systemFontOfSize:20.0], NSFontAttributeName, nil]];
`
没有任何效果

**Comment by rickytan** [comment]
直接改 root navigation controller ，然后设置 `transferNavigationBarAttributes` 设置为 **YES** 也可以的

**Comment by songhailiang** [comment]
嗯，但是我觉得这样可能用起来并不是很方便，因为App里很有可能会present其他的NavigationController，这样的话就得设置每个NavigationController的样式。UINavigationBar appearance是设置默认样式的，我觉得应该支持一下比较好。
您的这个库正式我所需要的，因为我的APP已经完成了，如果要使用的话，可能改动会比较大，我还在评估修改量。非常感谢！

**Comment by rickytan** [comment]
如果你用的 **storyboard** ，只要改个 Class 名 😄 
有空再看，本应该直接支持的

**Comment by songhailiang** [comment]
我大概找到原因了，是在transferNavigationBarAttributes=YES时，给self.navigationBar设置样式时没有考虑appearance里的值，我改成这样就可以了，不知道代码严不严谨，还望指教：
`self.navigationBar.tintColor       = [UINavigationBar appearance].tintColor ?: self.navigationController.navigationBar.tintColor;`

**Comment by rickytan** [comment]
那你设置为 **NO** 试试？

**Comment by rickytan** [comment]
我试过了，是直接支持的，你要在最开始设置  **appearance**

**Comment by rickytan** [comment]
第一个有用，后来 push 的没用，已修复
