### ISSUE TITLE
关于导航栏自定义的问题

### ISSUE THREAD

**Issue by loveJuly** [rickytan/RTRootNavigationController#120]
导入nav的category类文件，遇到改变导航栏的背景色、透明度等会失效的问题。

**Comment by rickytan** [comment]
看你怎么改的，代码放一下

**Comment by loveJuly** [comment]
- (void)lt_setBackgroundColor:(UIColor *)backgroundColor
{
    if (!self.overlay) {
        [self setBackgroundImage:[UIImage new] forBarMetrics:UIBarMetricsDefault];
        self.overlay = [[UIView alloc] initWithFrame:CGRectMake(0, 0, CGRectGetWidth(self.bounds), CGRectGetHeight(self.bounds) + 20)];
        self.overlay.userInteractionEnabled = NO;
        self.overlay.autoresizingMask = UIViewAutoresizingFlexibleWidth;    // Should not set `UIViewAutoresizingFlexibleHeight`
        [[self.subviews firstObject] insertSubview:self.overlay atIndex:0];
    }
    self.overlay.backgroundColor = backgroundColor;
}

**Comment by loveJuly** [comment]
- (UIView *)overlay
{
    return objc_getAssociatedObject(self, &overlayKey);
}

- (void)setOverlay:(UIView *)overlay
{
    objc_setAssociatedObject(self, &overlayKey, overlay, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
}

**Comment by loveJuly** [comment]
导航栏背景色、透明度等问题已解决（个人失误），剩下还想请教一个问题：返回按钮的自定义
UIImage *backButtonImage = [[UIImage imageNamed:@"back"]
                                resizableImageWithCapInsets:UIEdgeInsetsMake(0, 18, 0, 0)];
    [[UIBarButtonItem appearance] setBackButtonBackgroundImage:backButtonImage
                                                      forState:UIControlStateNormal
                                                    barMetrics:UIBarMetricsDefault];
    [[UIBarButtonItem appearance] setBackButtonTitlePositionAdjustment:UIOffsetMake(0, -60)
                                                         forBarMetrics:UIBarMetricsDefault];

这样自定义图片没有生效，是不是一定要通过- (UIBarButtonItem *)rt_customBackItemWithTarget:(id)target action:(SEL)action这个方法去自定义？

**Comment by rickytan** [comment]
对，因为那个不是真正的 backButton，是一个 leftItem
