### ISSUE TITLE
在原来的代码中使用到self.navigationController.viewControllers

### ISSUE THREAD

**Issue by swsdyg** [rickytan/RTRootNavigationController#13]
@rickytan 你好，我在原来的代码中使用到self.navigationController.viewControllers;直接使用您的这个项目好像会出问题，self.navigationController.viewControllers;返回的数组中正常情况下只会包含当前的vc，是不是需要重写一下viewControllers的getter方法，谢谢回答!

**Comment by rickytan** [comment]
是什么情况下需要直接用这个？你可以：
```objective-c
self.rt_navigationController.rt_viewControllers;
```
重写 `getter` 尚不清楚会不会造成隐患

**Comment by swsdyg** [comment]
其实我也注意到了，重写getter确实容易造成问题，我看了您的源码，我准备再封装一层使用来使用self.rt_navigationController.rt_viewControllers，我还想问一个问题，就是我在viewcontroller（不是navigationcontroller）的子类中重写了- (UIStatusBarStyle)preferredStatusBarStyle方法，但是不会调用，但我看您的调用没问题，不知您知道是什么原因吗，还望不吝赐教!

**Comment by rickytan** [comment]
你的 `viewController` 子类放在哪个里面？

**Comment by swsdyg** [comment]
我是说你在RTContainerController类中重写了- (UIStatusBarStyle)preferredStatusBarStyle方法会调用，而我自己写了一个UIViewController的子类，里面也重写了该方法但不会调用(我的工程还没引入您的项目，我只是单纯的请教问题，希望您不要见谅)，我一直不明白原因，所以想请教一下。
截图是您的代码，这个方法是会自动调用的
<img width="592" alt="screen shot 2016-07-14 at 11 08 00 am" src="https://cloud.githubusercontent.com/assets/8267484/16826885/dd5b5492-49b3-11e6-8f0f-b439e0d52ef8.png">
下面是我的代码，但该方法不会被调用 
<img width="308" alt="screen shot 2016-07-14 at 11 14 57 am" src="https://cloud.githubusercontent.com/assets/8267484/16826934/46cc4cce-49b4-11e6-8131-eff713b4be5b.png">

<img width="446" alt="screen shot 2016-07-14 at 11 14 08 am" src="https://cloud.githubusercontent.com/assets/8267484/16826938/513b3b48-49b4-11e6-9875-4557ec10ff12.png">

**Comment by rickytan** [comment]
1. 在 `Info.plist` 中设置 view controller based status bar 为 **YES**
2. 如果你的 VC 在系统的 Navigation 中，它不会被调到，Navigation 接管了

**Comment by swsdyg** [comment]
@rickytan  谢谢你，我找到原因了，其实你的根本没有设置view controller based status bar 为 YES
但你的RTContainerController中的- (UIStatusBarStyle)preferredStatusBarStyle方法会调用，是因为你的navigation bar是隐藏的，我实验了一下，如果我把自己写的navigation bar隐藏掉也是可以的，谢谢你!
![be6c86c7-2ce9-4314-a957-aeb80495ce88](https://cloud.githubusercontent.com/assets/8267484/16863556/a1fea1c8-4a86-11e6-8b42-762006cde70d.png)

**Comment by rickytan** [comment]
参考 #9
