### ISSUE TITLE
如何在导航栈中插入控制器？

### ISSUE THREAD

**Issue by slkai** [rickytan/RTRootNavigationController#130]
rt_viewControllers为只读，如果要在导航栈中插入控制器，只能自己创建RTContainerViewController-> RTContainerNavigationController -> MyViewController，再添加到导航栈中？

**Comment by rickytan** [comment]
插入控制器一般通过  push 在最后插入一个，你是要在之前插入一个？

**Comment by slkai** [comment]
是的，产品需求。现在只能fork把- (instancetype)initWithController:(UIViewController *)controller;放到头文件了，希望@rickytan 考虑一下兼容这种情况哈。

**Comment by rickytan** [comment]
这个是可以做的：
```objective-c
NSMutableArray *controllers = [self.rt_navigationController.rt_viewControllers mutableCopy];
// 在 controllers 中任意位置插入一个新的
self.rt_navigationController.viewControllers = [controllers copy];
```
