### ISSUE TITLE
无法手势返回

### ISSUE THREAD

**Issue by mumusa** [rickytan/RTRootNavigationController#132]
Xcode 8.3.3 && Xcode 9.0
真机和模拟器都无法手势返回
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    self.window = [[UIWindow alloc] init];
    self.window.backgroundColor = [UIColor clearColor];
    [self.window makeKeyAndVisible];
    self.window.frame = [UIScreen mainScreen].bounds;
    
    UITabBarController *tab = [[UITabBarController alloc] init];
    tab.viewControllers = @[[[RTContainerNavigationController alloc] initWithRootViewController:[ViewController new]],
                            [[RTContainerNavigationController alloc] initWithRootViewController:[ViewController1 new]],
                            [[RTContainerNavigationController alloc] initWithRootViewController:[ViewController2 new]],
                            [[RTContainerNavigationController alloc] initWithRootViewController:[ViewController3 new]]];
    
    self.window.rootViewController = [[RTRootNavigationController alloc] initWithRootViewControllerNoWrapping:tab];
    return YES;
}

=============================

unexpected nil window in __dispatchPreprocessedEventFromEventQueue, _windowServerHitTestWindow: <UIClassicWindow: 0x100305940; frame = (0 0; 768 1024); userInteractionEnabled = NO; gestureRecognizers = <NSArray: 0x17005c830>; layer = <UIWindowLayer: 0x170026f20>>

**Comment by rickytan** [comment]
window 的 frame 为 0，改为：
```objective-c
self.window = [[UIWindow alloc] initWithFrame:[UIScreem mainScreem].bounds];
```

**Comment by mumusa** [comment]
先设置frame效果一样 ，网易云音乐的i4.0.1 pa自签名到ipad mini上也是不能手势返回

**Comment by rickytan** [comment]
报的这个错误，应该是点击事件都没有分发，除了不能手势返回，点击拖动还有效吗？

**Comment by mumusa** [comment]
点击、滑动都是有效的
昨天在8.3.3 的模拟器上有时候可以响应返回，真机不行，和Xcode9.0.1（真机模拟器）都不行

**Comment by rickytan** [comment]
[这个](http://chaojihexiang.iteye.com/blog/2164872) 能不能解决您的问题？

**Comment by rickytan** [comment]
或者 `[self.window makeKeyAndVisible];` 放到最后 return YES 前再试试？

**Comment by mumusa** [comment]
感谢您耐心的回复🙏

**Comment by rickytan** [comment]
已经好了？

**Comment by mumusa** [comment]
没有呢

**Comment by mumusa** [comment]
我是采用纯代码方式创建的，您可以建个demo调试一下

**Comment by rickytan** [comment]
我自己的项目全是代码的，没有问题

**Comment by mumusa** [comment]
可否发个demo🙏
908427270
