### ISSUE TITLE
关于在viewDidLoad中获取self.view.safeAreaInsets

### ISSUE THREAD

**Issue by KarinoSharuru** [rickytan/RTRootNavigationController#136]
项目在适配iOS 11过程中有通过当前视图的safeAreaInsets值去进行布局的调整，或是一些UI联动效果的临界值判断。
然后在使用RTRootNavigationController时，发现viewDidLoad中获取时一直是UIEdgeInsetsZero。转到viewDidLayoutSubviews打印获取的结果是：
···························
 {0, 0, 0, 0}
 {0, 0, 0, 0}
 {88, 0, 34, 0}
 {88, 0, 34, 0}
···························
系统的导航控制器的话则是:
···························
 {88, 0, 34, 0}
 {88, 0, 34, 0}
···························
于是viewDidLoad中想拿到这个值进行相关设置的话就恒为零了。。本来是想通过这样的方式动态获取edge.bottom值，而不是根据iPhone机型和底部有无UITabBar写死bottom为34 or 83。但这样的话似乎就行不通了。

**Comment by rickytan** [comment]
你的 vc 是怎么初始化的？

**Comment by rickytan** [comment]
我用系统自带的，在 `- viewDidLoad` 中也确实是 {0, 0, 0, 0} 啊

**Comment by rickytan** [comment]
调整 UI 的代码应该放到 `- viewSafeAreaInsetsDidChange` 中，就像调整布局放到 `- viewDidLayoutSubviews` 一样

**Comment by KarinoSharuru** [comment]
结构的话就是常见的window.rootVC->UITabarController->@[NavigationVC，NavigationVC]
NavigationVC栈中的VC就是正常init后Push。

> 调整 UI 的代码应该放到 - viewSafeAreaInsetsDidChange 中，就像调整布局放到 - viewDidLayoutSubviews 一样

好的我试试，谢谢。

ps:目前的话我是改为了通过获取window.rootVC.view(也就是tabBarVC的)以确定当前机型的safeAreaInsets，然后再根据当前vc是否有隐藏导航栏or底部标签栏来确定布局调整。

**Comment by rickytan** [comment]
你这种需求完全可以用 topLayoutGuide 和 bottomLayoutGuide 来完成，全自动

**Comment by KarinoSharuru** [comment]
> 你这种需求完全可以用 topLayoutGuide 和 bottomLayoutGuide 来完成，全自动

嗯好谢谢，之前没怎么用过这个属性，我去看看。

> 我用系统自带的，在 - viewDidLoad 中也确实是 {0, 0, 0, 0} 啊

系统自带确实也是 {0, 0, 0, 0}，是我看错了，昨晚查看成NavigaitonVC.view去了，这两天适配iOS 11和iPhone X头都晕了😲
