### ISSUE TITLE
隐藏导航栏和状态栏跳转后，侧滑发现状态栏文字和图标不见了

### ISSUE THREAD

**Issue by weidongliu** [rickytan/RTRootNavigationController#139]
大神，如题，我遇到两个问题请教下
1.我用你的demo在RTStaticTableViewController隐藏状态栏和导航栏时，push到正常有导航栏和状态栏的控制器，然后侧滑会发现状态栏的文字和图标不见了？
隐藏导航栏和状态栏代码
```objective-c
- (void)viewDidLoad {
    [super viewDidLoad];
    [self.navigationController setNavigationBarHidden:YES animated:NO];
}

-(BOOL)prefersStatusBarHidden {
    return YES;
}
```
2.在状态栏和导航栏都隐藏的时候，跳转到导航栏透明的控制器(滚动式导航栏渐变为红色)，侧滑一点发现导航栏变成红色的了。
```objective-c
- (void)viewWillAppear:(BOOL)animated{
    [super viewWillAppear:animated];
    self.navigationController.navigationBar.backgroundColor = [UIColor clearColor];
    [self setNavgationBarViewClear];
}

//设置导航栏颜色
- (void)setNavgationBarViewClear {   
    UINavigationBar *navBar = self.navigationController.navigationBar;
    [navBar setBackgroundImage:[ImageUtils colorToImage:[UIColor clearColor]] forBarMetrics:UIBarMetricsDefault];
    [navBar setShadowImage:[[UIImage alloc]init]];
}
```
大神抽空看看能否解决

**Comment by rickytan** [comment]
放个截图上来，没太明白您的描述

**Comment by rickytan** [comment]
![image](https://user-images.githubusercontent.com/1250207/32382147-8a411e62-c082-11e7-9691-6668d1eb802f.png)
1. 是这样子？

**Comment by weidongliu** [comment]
对的对的，就是这样的

**Comment by rickytan** [comment]
这是正常的，前一个是隐藏的，返回就应该这样

**Comment by weidongliu** [comment]
👌

**Comment by rickytan** [comment]
第二个问题有截图吗？

**Comment by weidongliu** [comment]
![Uploading IMG_0228.JPG…]()

**Comment by weidongliu** [comment]
这页面默认导航栏透明，当往上滑动会改变透明度直到1.
![img_0228](https://user-images.githubusercontent.com/13080014/32429616-63e493b2-c306-11e7-8ba5-4d063dfb9496.JPG)
这是侧滑时候，导航栏直接显示了
![img_0226](https://user-images.githubusercontent.com/13080014/32429591-43ea296e-c306-11e7-883d-d6d80642dc64.JPG)

**Comment by weidongliu** [comment]
大神，这个我上次没仔细看代码，你这个没问题哈

**Comment by weidongliu** [comment]
是我同事代码里主动显示的
