### ISSUE TITLE
[[RTContainerNavigationController alloc] initWithRootViewController:vc2]

### ISSUE THREAD

**Issue by teng555teng** [rickytan/RTRootNavigationController#14]
tabController.viewControllers = @[[[RTContainerNavigationController alloc] initWithRootViewController:vc1],
                                  [[RTContainerNavigationController alloc] initWithRootViewController:vc2],
                                  [[RTContainerNavigationController alloc] initWithRootViewController:vc3],
                                  [[RTContainerNavigationController alloc] initWithRootViewController:vc4]];
self.window.rootViewController = [[RTRootNavigationController alloc] initWithRootViewControllerNoWrapping:tabController];

1. vc1,vc2,vc3, vc4  无法使用到UIViewController (RTRootNavigationController)中的rt_navigationBarClass

2.  UIViewController中无法获得UITabBarController

**Comment by rickytan** [comment]
2. vc1 2 3 4 应该都可以获取 tab controller 吧？
