### ISSUE TITLE
push时remove self, 新的viewcontroller会自动释放

### ISSUE THREAD

**Issue by fourse7en** [rickytan/RTRootNavigationController#143]
我在push时remove 了自身, 新的vc会pop会上一个vc, 怎么解决这个问题呢

**Comment by rickytan** [comment]
push 后才行，你代码怎么写的？

**Comment by fourse7en** [comment]
[self.rt_navigationController pushViewController:[[UIViewController alloc] init] animated:YES complete:^(BOOL finished) {
                [self.rt_navigationController removeViewController:self];
            }];

**Comment by fourse7en** [comment]
在viewDidLoad里面执行会自动释放

**Comment by rickytan** [comment]
你的 self 还在 push 的动画中，又 push 一个新的，本身操作就是不对的。应该等 self 完全  appear 之后再做。另外，这个 self 似乎没有存在的意义，只是中转了一下，自动  viewDidLoad 马上又 push 另一个，还把自身移除了
