### ISSUE TITLE
Push 多个页面后 我想保留最后一个页面，移除前面多个页面，发现无法移除

### ISSUE THREAD

**Issue by lijlk** [rickytan/RTRootNavigationController#145]
我从A页面一直Push到E页面， A->B->C->D->E ，NSArray *viewControllers = [self.rt_navigationController rt_viewControllers]; 我遍历了这个数组然后保留最后一个，用[self.rt_navigationController removeViewController:controller]; 这个方法分别移除B、C、D，但是结果去没有移除

**Comment by rickytan** [comment]
这里的 `self` 是 **E** 吗？

**Comment by lijlk** [comment]
self是D，因为我要push到E，返回的时候前面的页面都不需要显示了

**Comment by faimin** [comment]
在`E` 的 `viewDidAppear:` 中处理`removeViewController:`

**Comment by lijlk** [comment]
好像还是不行，无法移除掉

**Comment by rickytan** [comment]
先把 self.rt_navigationController 变量改下来，D 从导航中移除后，无法再通过  self.rt_navigationController 访问到了

**Comment by lijlk** [comment]
我把self.rt_navigationController 变量记下来后该怎么操作呢？

**Comment by rickytan** [comment]
```objc
RTRootNavigationController *nav = self.rt_navigationController;

NSArray <UIViewController *> *vcs = [self.rt_navigationController rt_viewControllers];
for (UIViewController *vc in vcs) {
    if (!A && !E) {
        [nav removeViewController:vc];
    }
} 
```

**Comment by lijlk** [comment]
我是在D中这样处理的，
      
        UIViewController *E = [[UIViewController alloc] init];
        RTRootNavigationController *nav = self.rt_navigationController;
        
        [self.rt_navigationController pushViewController:E animated:YES complete:^(BOOL finished)
        {
            NSArray <UIViewController *> *vcs = [self.rt_navigationController rt_viewControllers];
            for (UIViewController *vc in vcs) {
                if (!A && !E)
                {
                    [nav removeViewController:vc];
                }
             }
         }];

但是最后只有D被移除了，其他的页面无法移除

**Comment by rickytan** [comment]
单步跟进 removeViewController 方法看看发生了什么
```objc
- (void)removeViewController:(UIViewController *)controller animated:(BOOL)flag
{
    NSMutableArray<__kindof UIViewController *> *controllers = [self.viewControllers mutableCopy];
    __block UIViewController *controllerToRemove = nil;
    [controllers enumerateObjectsUsingBlock:^(__kindof UIViewController * obj, NSUInteger idx, BOOL * stop) {
        if (RTSafeUnwrapViewController(obj) == controller) {
            controllerToRemove = obj;
            *stop = YES;
        }
    }];
    if (controllerToRemove) {
        [controllers removeObject:controllerToRemove];
        [super setViewControllers:[NSArray arrayWithArray:controllers] animated:flag];
    }
}
```
controllerToRemove 有没有找到？

**Comment by wwdc14** [comment]
增加方法
`- (void)removeViewControllers:(NSArray<UIViewController *> *)viewContrViews animated:(BOOL)flag`

```- (void)removeViewControllers:(NSArray<UIViewController *> *)viewContrViews animated:(BOOL)flag
{
    NSMutableArray<__kindof UIViewController *> *controllers = [self.rt_viewControllers mutableCopy];
    NSArray *safeViews = [viewContrViews rt_map:^id(UIViewController *obj, NSUInteger index) {
        return RTSafeUnwrapViewController(obj);
    }];
    [controllers removeObjectsInArray:safeViews];
    NSMutableArray *newControllers = @[].mutableCopy;
    [self.viewControllers enumerateObjectsUsingBlock:^(__kindof UIViewController * _Nonnull vc1, NSUInteger idx, BOOL * _Nonnull stop) {
        
        [controllers enumerateObjectsUsingBlock:^(__kindof UIViewController * _Nonnull vc2, NSUInteger idx, BOOL * _Nonnull stop) {
            
            if (RTSafeUnwrapViewController(vc1) == vc2) {
                [newControllers addObject:vc1];
            }
            
        }];
        
    }];
    [super setViewControllers:[NSArray arrayWithArray:newControllers] animated:flag];
}`


调用

`NSArray * removeViewControllers = @[A,B,C,D];`

```[self.rt_navigationController pushViewController:E animated:YES complete:^(BOOL finished)
    {
       [weak_self.rt_navigationController removeViewControllers:removeViewControllers animated:NO];
     }];`

**Comment by lijlk** [comment]
if (controllerToRemove) {
        [controllers removeObject:controllerToRemove];
        [super setViewControllers:[NSArray arrayWithArray:controllers] animated:flag];
    }
这一步确实是remove掉了controllerToRemove在[super setViewControllers:[NSArray arrayWithArray:controllers] animated:flag];时controllers的数量是减少了，但是循环再进入这个方法的时候 NSMutableArray<__kindof UIViewController *> *controllers = [self.viewControllers mutableCopy];
得到的controllers的数量还是不变的，每次循环进来还都是那些controllers

**Comment by wwdc14** [comment]
@lijlk 之前也遇到类似你这样的情况，增加我上面👆那个方法 就可以解决了。

**Comment by lijlk** [comment]
@wwdc14 @rickytan 方法可行，非常感谢二位

**Comment by wwdc14** [comment]
🍻

**Comment by myeveryheart** [comment]
麻烦更新到库里呀亲们

**Comment by myeveryheart** [comment]
@rickytan 现在的代码还是会出问题。麻烦更新一下

**Comment by RockXeng** [comment]
麻烦更新库里啊，这个方法。

**Comment by mark0808** [comment]
gs
