### ISSUE TITLE
RTContainerController能否增加对HomeIndicator的显示隐藏

### ISSUE THREAD

**Issue by 736497373** [rickytan/RTRootNavigationController#147]
X上如果想HomeIndicator他自动淡化隐藏、需要在RTRootNavigationController加入
- (BOOL)prefersHomeIndicatorAutoHidden {
    return true;
}

作者是否能更新能让用户来自己设置是否开启呢

**Comment by rickytan** [comment]
这是个问题，感谢反馈！
