### ISSUE TITLE
调用[self.navigationItem setHidesBackButton:YES] 不生效，返回键依然显示

### ISSUE THREAD

**Issue by wanghanfeng** [rickytan/RTRootNavigationController#149]
如题，在demo上设置后也是相同！

**Comment by rickytan** [comment]
使用 `self.navigationItem.leftItem = nil;` 你看到的返回已经  `leftItem` 伪装成的了

**Comment by wanghanfeng** [comment]
我的意思并不是这样的，你上面的这种做法仅仅是给leftBarButtonItem赋了一个没有图片和文字的UIBarButtonItem对象，仅仅是看不到了，但是依旧存在于视图上，也可以接受点击事件。这样的话，系统的titleView不能使用leftBarButtonItem的空间来展示更多的内容，所以问题并没有解决。（如下图）
![image](https://user-images.githubusercontent.com/16850247/33052756-4fff972e-ceab-11e7-86df-61043a52fef2.png)

**Comment by rickytan** [comment]
重写 `rt_customBackBarButtonItemWithTarget:action:` 返回 nil 试试？

**Comment by wanghanfeng** [comment]
不好意思，我弄错了，这个leftBarButtonItem是子类添加的。:-D  
你之前self.navigationItem.leftItem = [UIBarButtonItem new];可以解决问题，视图层上没有leftBarButtonItem结构。

另外，你说重写````rt_customBackBarButtonItemWithTarget:action:````这个方法，我全局搜索了下 ，没有发现这个方法啊，你又更新框架了吗？

**Comment by rickytan** [comment]
https://github.com/rickytan/RTRootNavigationController/blob/67ef8131045de82794e4ca2b3e0e1f8d076f3074/RTRootNavigationController/Classes/UIViewController%2BRTRootNavigationController.h#L38

打错了
