### ISSUE TITLE
为何不支持全屏侧滑呢?

### ISSUE THREAD

**Issue by shanbozhu** [rickytan/RTRootNavigationController#15]

**Comment by rickytan** [comment]
1. 很容易误操作
2. 很容易与 table 的右滑动作等冲突

总体来说，全屏返回并不是一个好的交互方式，这也是苹果官方使用 ScreenEdgePan Gesture 的原因。微信的 Android 版自己实现了手势返回，也是边缘才有效。

**Comment by songhailiang** [comment]
我也是并不支持全屏侧滑。
