### ISSUE TITLE
分享一下实现思路

### ISSUE THREAD

**Issue by songyuanhang** [rickytan/RTRootNavigationController#151]
你好，看了一下源码，不是很明白你的实现思路。有时间可以分享一下，你的思想思路嘛。现在没有弄明白，隐藏了navigationbar,怎么让集成的控制器的view的frame自动偏移64的。

**Comment by rickytan** [comment]
只是最外层的隐藏了，里面又包了一个导航器，偏移由内部那个导航器控制的

**Comment by songyuanhang** [comment]
嗯。谢谢。你那里套了几层。看的蒙了。

**Comment by faimin** [comment]
@songyuanhang  你可以参考下@JNTian 的这篇 [博文](http://jerrytian.com/2016/01/07/%E7%94%A8Reveal%E5%88%86%E6%9E%90%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%E7%9A%84%E5%AF%BC%E8%88%AA%E6%8E%A7%E5%88%B6%E5%99%A8%E5%88%87%E6%8D%A2%E6%95%88%E6%9E%9C/)，里面说的思路与这个框架是一致的。

**Comment by rickytan** [comment]
👍
