### ISSUE TITLE
使用系统返回buttonItem为什么会引起增加内存问题？

### ISSUE THREAD

**Issue by winterWD** [rickytan/RTRootNavigationController#155]
## // @warning Set this to @b YES will @b INCREASE memory usage!
@property (nonatomic, assign) IBInspectable BOOL useSystemBackBarButtonItem;

**Comment by rickytan** [comment]
#22

**Comment by rickytan** [comment]
其实也没多多少，只是说明一下

**Comment by winterWD** [comment]
谢谢提示，我再仔细看看源码，深入了解下。
