### ISSUE TITLE
导航栏背景色和title颜色

### ISSUE THREAD

**Issue by wangkejiaGitHub** [rickytan/RTRootNavigationController#156]
怎么设置背景色和title颜色，以及左右两边item颜色，我设置了
self.navigationBar.tintColor = [UIColor lightGrayColor];
self.navigationBar.barTintColor = [UIColor lightGrayColor];
并不好使

**Comment by rickytan** [comment]
**VC** 的 `self` 上并没有添加 `navigationBar`，用
```objc
self.navigationController.navigationBar = xxx;
```
且只能在 `-viewDidLoad` 之后使用
