### ISSUE TITLE
使用框架setViewControllers后出现的问题

### ISSUE THREAD

**Issue by winterwd** [rickytan/RTRootNavigationController#158]
未调用前的导航栏
![image](https://user-images.githubusercontent.com/14071671/33604734-0568aab4-d9f2-11e7-95ea-5280e5aa2f7e.png)

使用nav.setViewControllers(vcs, animated: true)，然后返回，出现的bug
![image](https://user-images.githubusercontent.com/14071671/33604752-127bba7a-d9f2-11e7-8c1f-0307e2803873.png)

看了代码，暂时没有找到原因，希望作者予以指导！

**Comment by rickytan** [comment]
这是个已知问题 #153 ，你可以参考先解决业务问题，后面我看再怎么优化

**Comment by winterWD** [comment]
ok，谢谢回复！

**Comment by winterWD** [comment]
现在没出现这个bug了，但我不确定是否是解决了，后续继续观察吧，谢谢
