### ISSUE TITLE
怎么截取重写当前页面的返回按钮事件啊。。。求解

### ISSUE THREAD

**Issue by PinkJoker** [rickytan/RTRootNavigationController#159]

**Comment by rickytan** [comment]
```objc
- (UIBarButtonItem *)rt_customBackBarItemWithTarget:(id)target action:(SEL)action {
   return [[UIBarButtonItem alloc] initWithTitle:@"back" target:你的target action:你的action];
}
```

**Comment by PinkJoker** [comment]
在rt不作为项目入口的时候可行么




| |
宋永恒
|
|
邮箱：forever89678@163.com
|

签名由 网易邮箱大师 定制

在2017年12月07日 19:21，Ricky Tan 写道：
- (UIBarButtonItem *)rt_customBackBarItemWithTarget:(id)target action:(SEL)action {
   return [[UIBarButtonItem alloc] initWithTitle:@"back"target:你的target action:你的action];
}

**Comment by PinkJoker** [comment]
现在由于我的tabbar也是用的一个框架，但是要求必须作为入口，所以RT作为了tabbar的root，我尝试这样写，没反应是不是因为我现在整个架构的问题




| |
宋永恒
|
|
邮箱：forever89678@163.com
|

签名由 网易邮箱大师 定制

在2017年12月07日 19:23，Joker Song 写道：
在rt不作为项目入口的时候可行么




| |
宋永恒
|
|
邮箱：forever89678@163.com
|

签名由 网易邮箱大师 定制

在2017年12月07日 19:21，Ricky Tan 写道：
- (UIBarButtonItem *)rt_customBackBarItemWithTarget:(id)target action:(SEL)action {
   return [[UIBarButtonItem alloc] initWithTitle:@"back"target:你的target action:你的action];
}

**Comment by PinkJoker** [comment]
用的陈奕龙的tabbar




| |
宋永恒
|
|
邮箱：forever89678@163.com
|

签名由 网易邮箱大师 定制

在2017年12月07日 19:27，Joker Song 写道：
现在由于我的tabbar也是用的一个框架，但是要求必须作为入口，所以RT作为了tabbar的root，我尝试这样写，没反应是不是因为我现在整个架构的问题




| |
宋永恒
|
|
邮箱：forever89678@163.com
|

签名由 网易邮箱大师 定制

在2017年12月07日 19:23，Joker Song 写道：
在rt不作为项目入口的时候可行么




| |
宋永恒
|
|
邮箱：forever89678@163.com
|

签名由 网易邮箱大师 定制

在2017年12月07日 19:21，Ricky Tan 写道：
- (UIBarButtonItem *)rt_customBackBarItemWithTarget:(id)target action:(SEL)action {
   return [[UIBarButtonItem alloc] initWithTitle:@"back"target:你的target action:你的action];
}

**Comment by PinkJoker** [comment]
这样的话会有影响吗，麻烦给小弟解答一下，谢谢




| |
宋永恒
|
|
邮箱：forever89678@163.com
|

签名由 网易邮箱大师 定制

在2017年12月07日 19:28，Joker Song 写道：
用的陈奕龙的tabbar




| |
宋永恒
|
|
邮箱：forever89678@163.com
|

签名由 网易邮箱大师 定制

在2017年12月07日 19:27，Joker Song 写道：
现在由于我的tabbar也是用的一个框架，但是要求必须作为入口，所以RT作为了tabbar的root，我尝试这样写，没反应是不是因为我现在整个架构的问题




| |
宋永恒
|
|
邮箱：forever89678@163.com
|

签名由 网易邮箱大师 定制

在2017年12月07日 19:23，Joker Song 写道：
在rt不作为项目入口的时候可行么




| |
宋永恒
|
|
邮箱：forever89678@163.com
|

签名由 网易邮箱大师 定制

在2017年12月07日 19:21，Ricky Tan 写道：
- (UIBarButtonItem *)rt_customBackBarItemWithTarget:(id)target action:(SEL)action {
   return [[UIBarButtonItem alloc] initWithTitle:@"back"target:你的target action:你的action];
}

**Comment by rickytan** [comment]
只要是 vc 的导航器就行的，不一定作为 rootViewController

**Comment by rzshuo** [comment]
放到我的UIViewController里，一点反应没有，都没走这。
`- (UIBarButtonItem *)rt_customBackBarItemWithTarget:(id)target action:(SEL)action {
    UIBarButtonItem *backButtonItem = [[UIBarButtonItem alloc] init];
    backButtonItem.title = @"22334";
    backButtonItem.target = target;
    backButtonItem.action = action;
    return backButtonItem;
}`

**Comment by rzshuo** [comment]
放到我的UIViewController里，一点反应没有，都没走这。
- (UIBarButtonItem *)rt_customBackBarItemWithTarget:(id)target action:(SEL)action {
    UIBarButtonItem *backButtonItem = [[UIBarButtonItem alloc] init];
    backButtonItem.title = @"22334";
    backButtonItem.target = target;
    backButtonItem.action = action;
    return backButtonItem;
}
