### ISSUE TITLE
接听电话时操作app 切换界面时UINavigationBar 怪异

### ISSUE THREAD

**Issue by teng555teng** [rickytan/RTRootNavigationController#16]
![Uploading QQ截图20160805155357.png…]()
接听电话时操作app 切换界面时UINavigationBar 怪异

**Comment by teng555teng** [comment]
![qq 20160805155357](https://cloud.githubusercontent.com/assets/4971709/17431542/22b1f50c-5b2d-11e6-93e5-fd7710f20f0a.png)

**Comment by teng555teng** [comment]
切换界面时会很怪异 不过 bar会先跳一下 然后就恢复正常了

**Comment by rickytan** [comment]
你是不是用了 [UIScreen mainScreen].bounds.size.height 了？布局都用相对，不要用写死的高，应该没问题的

**Comment by teng555teng** [comment]
都是 相对布局

**Comment by rickytan** [comment]
什么系统？

**Comment by teng555teng** [comment]
测试环境：iphone6 ios 9.3.2 型号MG492ZP/A  
我在切换的时候 VC 的edgesForExtendedLayout 属性有变化 问题应该出在这里

**Comment by teng555teng** [comment]
我测试你下你的demo 也有这个问题跟edgesForExtendedLayout没有关系 而网易云音乐没有这个问题

**Comment by rickytan** [comment]
最近太忙了，感谢反馈！

**Comment by leewei716** [comment]
- (void)willMoveToParentViewController:(UIViewController *)parent{
    
}

-(void)didMoveToParentViewController:(UIViewController *)parent{
    
    
}使用你的这个导航栏后，返回时，这个方法不走，

**Comment by leewei716** [comment]
如果有知道的朋友怎么处理，麻烦给我说一下谢谢，我的邮箱287809258@qq.com

**Comment by rickytan** [comment]
@leewei716 这个会走的，只是时机与原来不一样
