### ISSUE TITLE
关于每个控制器自定义一个UINavgationBar

### ISSUE THREAD

**Issue by uncleRX** [rickytan/RTRootNavigationController#160]
我发现demo中自定义的bar 有一个方法

- (Class)rt_navigationBarClass{
   return  [RTCustomNavigationBar class];
}
我自己要定义一个自定义类型的话
首先我想到是自己继承一个系统的 navgationBar,然后在这个方法中返回,可是我感觉不怎么起效果..这个方法生命周期不进 - init 里面自定义的一公共件操作起来不是很方便,我现在应该怎么处理这个问题

**Comment by uncleRX** [comment]
三个页面返回三个自定义的navgationBar的需求,直接通过(Class)rt_navigationBarClass{} 可以实现么? 请问是需要在当前控制器又另外自己设置一大堆属性么? 想在自定义navgationBar直接类里直接把逻辑写好,控制器直接得到这个返回类型就行了,目前能返回类型,但是效果不好.....demo里仅仅 在drawRect方法里绘制了一下~ 有没有更详细点的方案

**Comment by rickytan** [comment]
这个方法可以进的
```objc
@implementation RTCustomNavigationBar
- (instancetype)initWithFrame:(CGRect)frame
{
    self = [super initWithFrame:frame];
    if (self) {
        
    }
    return self;
}
@end
```

**Comment by rickytan** [comment]
太部分情况，您并不需要自定义一个 **Bar**，用它的设置方法添加背景，改变颜色就可以实现了，这里只是为了一些很特殊的情况用的

**Comment by uncleRX** [comment]
楼主自定义bar的时候 有处理iPhone X 顶部的视图空缺的模块吗(状态栏那块)
![o1m2hwqaaaabjru5erkjggg](https://user-images.githubusercontent.com/16251490/33825612-2728d87c-de9d-11e7-8cb5-8d6a4e7474cd.png)
?

**Comment by uncleRX** [comment]
谢谢~ 已经处理
