### ISSUE TITLE
和Aspects第三方冲突

### ISSUE THREAD

**Issue by Attu7** [rickytan/RTRootNavigationController#165]
在hook, viewWillAppear时会报
Unbalanced calls to begin/end appearance transitions for <RTContainerController: 0x145d74a50>.
错误。

**Comment by rickytan** [comment]
从实践中来看，Aspects 可能引发的问题多了去了，可以用来测试，但最好不要线上引用

**Comment by rickytan** [comment]
比如，这个<https://toutiao.io/posts/yvr17c/preview>
