### ISSUE TITLE
与FDFullscreenPopGesture冲突

### ISSUE THREAD

**Issue by ChenZhenChun** [rickytan/RTRootNavigationController#166]
使FDFullscreenPopGesture  警用全局返回失效
原因：self.navigationController.viewControllers.lastObject 返回的是RTContainerController类型对象

**Comment by ChenZhenChun** [comment]
需要使用self.rt_navigationController.viewControllers.lastObject.fd_interactivePopDisabled = YES;才能兼容FDFullscreenPopGesture  希望RTRootNavigationController能做一下兼容

**Comment by rickytan** [comment]
如果您只是需要全屏侧滑返回，您可以参考 #17 ，无需引入  [FDFullscreenPopGesture](https://github.com/forkingdog/FDFullscreenPopGesture)
