### ISSUE TITLE
自定义导航按钮，返回按钮距离最左边有缝隙

### ISSUE THREAD

**Issue by AntHuiZi** [rickytan/RTRootNavigationController#169]
在baseViewController用以下方法自定义，
```objective-c
- (UIBarButtonItem *)customBackItemWithTarget:(id)target action:(SEL)action
{
    UIButton *button = [UIButton buttonWithType:UIButtonTypeCustom];
    button.backgroundColor = [UIColor redColor];

    [button setImage:[UIImage imageNamed:@"arrow_left"] forState:UIControlStateNormal];
    [button setImage:[UIImage imageNamed:@"arrow_left_highlight"] forState:UIControlStateHighlighted];
//    [button sizeToFit];
    button.frame = CGRectMake(0, 0, 60, 44);
    [button addTarget:target
               action:action
     forControlEvents:UIControlEventTouchUpInside];
    return [[UIBarButtonItem alloc] initWithCustomView:button];
    
}
```
![img_2022](https://user-images.githubusercontent.com/18253873/34428658-2ce1208a-ec8a-11e7-8d35-60912398b216.PNG)

**Comment by rickytan** [comment]
这个是系统默认留的，你可以试试改一下 `setTitlePositionAdjustment` 或者 `imageInsets`

**Comment by AntHuiZi** [comment]
恩，好的，非常感谢您的帮助。
我是通过以下两行代码修改的：
leftBtn.contentHorizontalAlignment =UIControlContentHorizontalAlignmentLeft;
 [leftBtn setImageEdgeInsets:UIEdgeInsetsMake(0,-7,0,7)];

**Comment by ClearWB** [comment]
这个问题的话，能请问下如何扩大这个左侧返回按钮的点击区域嘛，意思是向左扩展，点击系统预留的区域也能响应返回事件

**Comment by rickytan** [comment]
你可以通过  UIBarButtonItem + customView 实现，你自定一个 UIView 的子类，覆盖 pointInside 方法
