### ISSUE TITLE
只针对导航条优化，如果需要做全屏侧滑返回怎么办？

### ISSUE THREAD

**Issue by yangzhixiao** [rickytan/RTRootNavigationController#17]
全屏侧滑返回，或者距离左侧一定距离才触发，请问这个怎么做？

**Comment by rickytan** [comment]
https://github.com/forkingdog/FDFullscreenPopGesture

**Comment by userdefault** [comment]
创建一个navigationcontroler继承RTRootNavigationController
@interface BaseNavigationController () <UIGestureRecognizerDelegate>

@end

@implementation BaseNavigationController

- (void)viewDidLoad {
    [super viewDidLoad];
    
    // 获取系统自带滑动手势的target对象
    id target = self.interactivePopGestureRecognizer.delegate;
    // 创建全屏滑动手势，调用系统自带滑动手势的target的action方法
    UIPanGestureRecognizer *pan = [[UIPanGestureRecognizer alloc] initWithTarget:target action:@selector(handleNavigationTransition:)];
    // 设置手势代理，拦截手势触发
    pan.delegate = self;
    // 给导航控制器的view添加全屏滑动手势
    [self.view addGestureRecognizer:pan];
    // 禁止使用系统自带的滑动手势
    self.interactivePopGestureRecognizer.enabled = NO;
    
}

// 什么时候调用：每次触发手势之前都会询问下代理，是否触发。
// 作用：拦截手势触发
- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer *)gestureRecognizer
{
    // 注意：只有非根控制器才有滑动返回功能，根控制器没有。
    // 判断导航控制器是否只有一个子控制器，如果只有一个子控制器，肯定是根控制器
    if (self.childViewControllers.count == 1) {
        // 表示用户在根控制器界面，就不需要触发滑动手势，
        return NO;
    }
    return YES;
}

**Comment by userdefault** [comment]
全屏侧滑返回方法如下：
创建一个navigationcontroler继承RTRootNavigationController
@interface BaseNavigationController () <UIGestureRecognizerDelegate>

@end

@implementation BaseNavigationController

- (void)viewDidLoad {
    [super viewDidLoad];
    
    // 获取系统自带滑动手势的target对象
    id target = self.interactivePopGestureRecognizer.delegate;
    // 创建全屏滑动手势，调用系统自带滑动手势的target的action方法
    UIPanGestureRecognizer *pan = [[UIPanGestureRecognizer alloc] initWithTarget:target action:@selector(handleNavigationTransition:)];
    // 设置手势代理，拦截手势触发
    pan.delegate = self;
    // 给导航控制器的view添加全屏滑动手势
    [self.view addGestureRecognizer:pan];
    // 禁止使用系统自带的滑动手势
    self.interactivePopGestureRecognizer.enabled = NO;
    
}
- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer *)gestureRecognizer
{
    // 注意：只有非根控制器才有滑动返回功能，根控制器没有。
    // 判断导航控制器是否只有一个子控制器，如果只有一个子控制器，肯定是根控制器
    if (self.childViewControllers.count == 1) {
        // 表示用户在根控制器界面，就不需要触发滑动手势，
        return NO;
    }
    return YES;
}

**Comment by clearlovelyQ** [comment]
你好，我自定义了一个导航控制器继承自`RTRootNavigationController `,在控制器里面加入了 @userdefault 的代码，确实是实现了全屏侧滑的功能，但是我发现，`rt_disableInteractivePop = YES`失效了，不能禁止某个vc的侧滑效果了，不知道是不是我自己设置的不对，大佬要是要时间的话，帮忙解答一下，万分感谢

**Comment by mssjwddplu** [comment]
遇到了 @clearlovelyQ 一样的问题，求大佬解答。
