### ISSUE TITLE
隐藏导航还能够实现侧滑吗?

### ISSUE THREAD

**Issue by vistaLin** [rickytan/RTRootNavigationController#172]
1.我隐藏了导航栏就无法实现侧滑[self.navigationController setNavigationBarHidden:YES];
2.我使用了[self.rt_navigationController setNavigationBarHidden:YES]有并没办法支持导航栏侧滑,是不支持还是有我不知道的方法?

**Comment by rickytan** [comment]
用 `self.navigationController.navigationBarHidden = YES` 正常使用情况下，**VC** 不需要知道本项目的存在。
在隐藏 bar 时系统默认行为是禁止手势返回的，本项目保留了这个行为，不过可以显示开启：
```objc
- (void)viewDidLoad {
  [super viewDidLoad];
  self.rt_disableInteractivePop = NO;
  ...
}
```

**Comment by vistaLin** [comment]
好的!谢谢
