### ISSUE TITLE
Demo完善建议

### ISSUE THREAD

**Issue by hstdt** [rickytan/RTRootNavigationController#176]
Demo里面没有rt_customBackItemWithTarget和useSystemBackBarButtonItem相关的内容，导致我看了源码才找到使用办法，而且和gif图也不一致。

**Comment by rickytan** [comment]
Demo 中使用了 `storyboard`，可以在界面设计器中设置：
![image](https://user-images.githubusercontent.com/1250207/35469465-2d0df45a-0370-11e8-9a98-9a9738da8fb0.png)

当然最关键还是看注释文档哈

**Comment by hstdt** [comment]
好吧。
