### ISSUE TITLE
如何设置默认的返回按钮样式

### ISSUE THREAD

**Issue by hstdt** [rickytan/RTRootNavigationController#177]
对于其他的三方库控件，不便于手动设置其返回按钮样式，又不想用默认的"Back"文字，请问应该如何设置一个自定义的UIBarButtonItem样式？

**Comment by rickytan** [comment]
具体哪个第三方库？有源码么？它不提供修改的方法吗？

**Comment by hstdt** [comment]
@rickytan  一般控件自己定制navigationBar的返回按钮的话，反倒会很容易和之前用户自定义的冲突吧。

**Comment by rickytan** [comment]
一般来说，项目一开始就应该定制一个自己的基类，如：MyBaseViewController，MyBaseTableViewController，其他 VC 都从这里继承，而不是系统的，这里方便做一些统一的操作，如页面跳转的打点。这样的话，在基类中实现 `-rt_customBackBarButtonItemWithTarget:action:` 方法就可以了

**Comment by hstdt** [comment]
其实主要是想由用户进行自定义leftBarButtonItem的样式。

![image](https://user-images.githubusercontent.com/10215098/35603877-7639a9f0-067a-11e8-9033-4a74a03c6394.png)

**Comment by rickytan** [comment]
这种你只能继承它再封装一次了。或者你在自己的 UIViewController  category 中实现 `rt_customBackItemWithTarget:action:`， 这样就统一实现了，本项目只定了接口并没有实现，你的 category 不会被覆盖

**Comment by hstdt** [comment]
新建一个category里面不使用@objc不会响应respondsToSelector

![image](https://user-images.githubusercontent.com/10215098/35720285-eeb374e8-0827-11e8-80bd-296a73b9ed46.png)

使用@objc，则有Error提示，和`UIViewController+RTRootNavigationController.h`中的`- (UIBarButtonItem *)rt_customBackItemWithTarget:(id)target action:(SEL)action;`冲突了。

![image](https://user-images.githubusercontent.com/10215098/35720257-cce1a704-0827-11e8-8b46-b533b2be82de.png)

这里有2个想法，大大看看可以么。

![image](https://user-images.githubusercontent.com/10215098/35720536-15318208-0829-11e8-8fad-47a413d928a4.png)

**Comment by hstdt** [comment]
如果用上面说的方案二，实现起来就很清爽了，甚至都不需要import，谢谢！

![image](https://user-images.githubusercontent.com/10215098/35721569-9a4a1c9e-082d-11e8-83aa-7ed0b1b6d6ba.png)

**Comment by rickytan** [comment]
用 **OC** 实现好像并不会冲突，**Swift** 之前没有考虑到
```objc
@interface UIViewController (abc)

@end

@implementation UIViewController (abc)

- (UIBarButtonItem *)rt_customBackItemWithTarget:(id)target action:(SEL)action
{
    return [[UIBarButtonItem alloc] initWithTitle:@"abc"
                                            style:UIBarButtonItemStyleDone
                                           target:target
                                           action:action];
}

@end
```
![image](https://user-images.githubusercontent.com/1250207/35725342-04f59ad8-083c-11e8-9cba-b2b5d62218c8.png)

**Comment by hstdt** [comment]
最终发现最主要的障碍在Swift这里。。 😓
我去想想有没有更好的办法解决这个编译问题。

**Comment by Lee0820** [comment]
> 最终发现最主要的障碍在Swift这里。。 😓
> 我去想想有没有更好的办法解决这个编译问题。

swift 最后怎么解决的，大佬
