### ISSUE TITLE
没继承别的框架，为什么要加pod，不开森

### ISSUE THREAD

**Issue by Xmanzn** [rickytan/RTRootNavigationController#18]

**Comment by rickytan** [comment]
不太明白你说的什么

**Comment by Xmanzn** [comment]
@rickytan  就是我在下载demo的时候 cocopods除了点问题，你好像也没引入其他框架吧，你这个原理是push 嵌套导航栏的vc 么，下班还没来得及看你源码

**Comment by faimin** [comment]
@Xmanzn  demo down下来之后重新pod update或者install一下，就好了
