### ISSUE TITLE
是否应该增强一下，侧滑返回的API。

### ISSUE THREAD

**Issue by leavesster** [rickytan/RTRootNavigationController#187]
看了 [issue-134](https://github.com/rickytan/RTRootNavigationController/issues/134), [issue-173](https://github.com/rickytan/RTRootNavigationController/issues/173)

目前，如果某个ViewController设置了 `leftBarButtonItem` 或者 `隐藏导航栏` 后需要在对应的 `ViewController` 设置下 `self.rt_disableInteractivePop = NO;` 
虽然这个行为和系统一致，但是感觉系统在这种情况下的处理，更为通用一些，代码量会更少一些。

```
self.navigationController.interactivePopGestureRecognizer.delegate = (id<UIGestureRecognizerDelegate>)self;
```

系统只需要在rootVC上设置以上代码，处理手势的delegate即可。这样就可以使得在这个视图栈推出的ViewControllers 全部有一个通用的操作，而不需要一个个单独给ViewController设置。代码量上，也更方便从系统的navigationController 迁移到 `RTRootNavigationController`
而且在推送了一系列视图后，突然有某一个ViewController不允许侧滑返回；在交互上，应该是一件蛮奇怪的事情。

所以，我想，是不是也可以给 `RTRootNavigationController` 加这么一个参数。又或者，重写 `RTRootNavigationController` 的 `interactivePopGestureRecognizer` 属性，把这个操作和 `navigationController.interactivePopGestureRecognizer.delegate` 的操作对应上。

如果作者也觉得有必要的话，我可以去实现下这个API，然后再提个PR。 ^_^

**Comment by rickytan** [comment]
个人感觉没必要，不过你可以 fork 实现自己的

**Comment by leavesster** [comment]
好的，那我自己fork简单加个BOOL值就完事了，不去考虑其他情况了。
