### ISSUE TITLE
请问可以和系统导航条无缝切换吗?

### ISSUE THREAD

**Issue by MQL9011** [rickytan/RTRootNavigationController#188]
比如 页面A是用的系统导航条
然后 push到页面B是用的RTRootNavi 
这种可以吗

**Comment by rickytan** [comment]
不建议这么做，结构会比较乱

**Comment by Charlschun** [comment]
用RTRootNavC（nav）放tabbar，tabbar里放四个RTRootNavC，然后[self.window setRootViewController:nav];  设置导航栏的title和背景颜色都失效了

**Comment by rickytan** [comment]
@Charlschun 这种场景下 tabBar 就是 root，外面不要再包 nav
