### ISSUE TITLE
关于README里，Notice中视图结构的一点疑惑

### ISSUE THREAD

**Issue by leavesster** [rickytan/RTRootNavigationController#189]
[noticeonly-for-below-v06](https://github.com/rickytan/RTRootNavigationController#noticeonly-for-below-v06)
应该是说的在0.6以前，没有修改 RTContainerNavigationController 的 ViewControllers 属性时， self.navigationController.viewControllers 永远为1吧。

但是我看 `ViewController hierarchy` 这部分，也在这个Notice中。是说0.6以后，这部分发生也发生了改变吗？

我看了下视图栈和git 记录，似乎0.6以后的版本，没有变化视图结构的变化。是包含错了还是我有什么地方没理解对吗？

**Comment by rickytan** [comment]
结构没有变，只是  `- viewControllers` 方法的实现改成了返回上一级 `navigationController` 的 **viewControllers**

**Comment by leavesster** [comment]
OK，看来没理解错。谢谢。可能README也拆分出来，会比较合适一点吧。
