### ISSUE TITLE
一用UIAlertController就挂掉

### ISSUE THREAD

**Issue by littlepoem** [rickytan/RTRootNavigationController#19]
错误信息如下：
2016-08-29 10:47:52.136 RTRootNavigationController_Example[53635:10524179] **\* Assertion failure in -[UIAlertController supportedInterfaceOrientations], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3512.60.7/UIAlertController.m:542
2016-08-29 10:47:52.141 RTRootNavigationController_Example[53635:10524179] **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UIAlertController:supportedInterfaceOrientations was invoked recursively!'
**\* First throw call stack:
(
    0   CoreFoundation                      0x000000010a1aad85 **exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x0000000109c1edeb objc_exception_throw + 48
    2   CoreFoundation                      0x000000010a1aabea +[NSException raise:format:arguments:] + 106
    3   Foundation                          0x0000000107c03d5a -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
    4   UIKit                               0x0000000108302313 -[UIAlertController supportedInterfaceOrientations] + 316
    5   RTRootNavigationController_Example  0x0000000107a9c7f6 -[RTRootNavigationController supportedInterfaceOrientations] + 70
    6   UIKit                               0x0000000108302258 -[UIAlertController supportedInterfaceOrientations] + 129
    7   UIKit                               0x0000000108193d6c -[UIViewController __supportedInterfaceOrientations] + 701
    8   UIKit                               0x00000001081943c5 -[UIViewController __withSupportedInterfaceOrientation:apply:] + 45
    9   UIKit                               0x0000000108194c59 -[UIViewController setInterfaceOrientation:] + 145
    10  UIKit                               0x000000010817d9a3 -[UIViewController viewDidMoveToWindow:shouldAppearOrDisappear:] + 1458
    11  UIKit                               0x000000010808f58c -[UIView(Internal) _didMoveFromWindow:toWindow:] + 1609
    12  UIKit                               0x0000000108084562 __45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke + 155
    13  Foundation                          0x0000000107b8d3d3 -[NSISEngine withBehaviors:performModifications:] + 155
    14  UIKit                               0x0000000108084480 -[UIView(Hierarchy) _postMovedFromSuperview:] + 575
    15  UIKit                               0x000000010809226c -[UIView(Internal) _addSubview:positioned:relativeTo:] + 1967
    16  UIKit                               0x00000001082ebd63 -[_UIAlertControllerPresentationController presentationTransitionWillBegin] + 208
    17  UIKit                               0x000000010814af44 __71-[UIPresentationController _initViewHierarchyForPresentationSuperview:]_block_invoke + 2035
    18  UIKit                               0x0000000108148b76 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke + 309
    19  UIKit                               0x0000000107fe6f62 _runAfterCACommitDeferredBlocks + 317
    20  UIKit                               0x0000000107ffae4c _cleanUpAfterCAFlushAndRunDeferredBlocks + 95
    21  UIKit                               0x0000000108007147 _afterCACommitHandler + 90
    22  CoreFoundation                      0x000000010a0cfc37 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION** + 23
    23  CoreFoundation                      0x000000010a0cfba7 __CFRunLoopDoObservers + 391
    24  CoreFoundation                      0x000000010a0c57fb __CFRunLoopRun + 1147
    25  CoreFoundation                      0x000000010a0c50f8 CFRunLoopRunSpecific + 488
    26  GraphicsServices                    0x000000010c48dad2 GSEventRunModal + 161
    27  UIKit                               0x0000000107fdaf09 UIApplicationMain + 171
    28  RTRootNavigationController_Example  0x0000000107a9527f main + 111
    29  libdyld.dylib                       0x000000010b3e792d start + 1
    30  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by userdefault** [comment]
http://stackoverflow.com/questions/31406820/uialertcontrollersupportedinterfaceorientations-was-invoked-recursively可以解决你的问题

**Comment by rickytan** [comment]
👍 @userdefault
