### ISSUE TITLE
请问能否增加设置某一导航控制器下的导航栏样式的功能？ 

### ISSUE THREAD

**Issue by likeSo** [rickytan/RTRootNavigationController#194]
需求大致为：某一页面present出一个navigationController，此时的这个navigationController的样式是区别于App全局样式（UINavigationBar.appearance()）的。

问题是，能否增加为此时的这个navigationController下的所有navigationBar设置单独样式的接口？

**Comment by rickytan** [comment]
在 `- viewDidLoad` 中直接改就好

**Comment by likeSo** [comment]
我知道可以这样改，但是这样只能改一个页面啊，我是说能否增加一个，统一设置这个导航控制器下以及其所有push出来的导航栏的样式，但是又不影响其他导航控制器的接口。

比如登录注册页面是模态出来的一个RTRootNavigationController，我想统一设置这个RTRootNavigationController下所有导航栏的样式，比如`navigationItem.title`，比如`left/rightBarButtonItem`的样式。

希望能添加这样的接口

**Comment by rickytan** [comment]
你可以这样：
```objc
- (void)onPresend:(id)sender
{
    VC *yourVC = ...;
    RTRootNavigationController *nav = [[RTRoot alloc] init];
    nav.navigationBar // 修改成你要的样式
    nav.transferNavigationBarAttributes = YES;    // 让后面进来的 vc 都带上样式
    [nav push: yourVC animated: NO];

   [self present: nav animated: YES];
}
```

**Comment by likeSo** [comment]
多谢！！以前没有看到你这块的代码，抱歉
