### ISSUE TITLE
当页面中存在UI移动的时候，push和pop会导致UI变形

### ISSUE THREAD

**Issue by Hoony-HU** [rickytan/RTRootNavigationController#198]
当UI设置了anchorPoint实现点击拖拽的时候发现返回的时候center变成了初始化的状态 导致ui变形

**Comment by rickytan** [comment]
代码放一下，感觉你应该用错了

**Comment by Hoony-HU** [comment]
- (void)touchesBegan:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event
{
    UITouch *touch = [touches anyObject];
    CGPoint currentLoc = [touch locationInView:self];
    [self.layer setAnchorPoint:CGPointMake(currentLoc.x / CGRectGetWidth(self.bounds), currentLoc.y / CGRectGetHeight(self.bounds))];
    currentLoc = [touch locationInView:self.superview];
    self.center = currentLoc;
}

- (void)touchesMoved:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event
{
    
    
    UIWindow * window = [UIApplication sharedApplication].keyWindow;
    CGRect showRect = [self convertRect:self.bounds toView:window];
//    74
    CGFloat maxY = CGRectGetMaxY(showRect);
    
    UITouch *touch = [touches anyObject];
    CGPoint currentLoc = [touch locationInView:self.superview];
    CGPoint centerP = self.center;
    
    if (maxY < __HOO_SCREEN_HEIGHT__ + 44)
    {
        self.open = YES;
    }else
    {
        self.open = NO;
    }
    
    if (maxY < __HOO_SCREEN_HEIGHT__)
    {
        if (centerP.y < currentLoc.y)
        {
            centerP.y = currentLoc.y;
        }
        self.center = centerP;
    }else if (maxY > __HOO_SCREEN_HEIGHT__ + 148 - 50)
    {
        if (centerP.y > currentLoc.y)
        {
            centerP.y = currentLoc.y;
        }
        self.center = centerP;
    } else
    {
        centerP.y = currentLoc.y;
        self.center = centerP;
    }
//    imageView.transform = CGAffineTransformMakeRotation(angle * (M_PI / 180.0f));
}

- (void)touchesEnded:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event
{
    [self checkAnimation];
}

- (void)checkAnimation
{
    CGRect finalRect;
    CGFloat bottomY = CGRectGetHeight(self.superview.bounds);
    if (self.open)
    {
        
        finalRect = CGRectMake(0, bottomY - 148 - kBottomSafeHeight, __HOO_SCREEN_WIDTH__, 148);
        
    }else
    {
        finalRect = CGRectMake(0, bottomY - 50 - kBottomSafeHeight, __HOO_SCREEN_WIDTH__, 148);
    }
    
//    __block ISAReplacementDragView * blockSelf = self;
    [UIView animateWithDuration:0.2 delay:0 options:UIViewAnimationOptionCurveEaseInOut animations:^{
        self.frame = finalRect;
        _addBtn.transform = CGAffineTransformMakeTranslation(0, self.open ? 0 : 120);
    } completion:^(BOOL finished) {
//        self.layer.anchorPoint = CGPointMake(0.5, 0.5);
        NSLog(@"center--%@",NSStringFromCGPoint(self.center));
        NSLog(@"anchorPoint--%@",NSStringFromCGPoint(self.layer.anchorPoint));
    }];
}

**Comment by rickytan** [comment]
这里几个问题：
1. 做拖拽动画，最好用 UIPanGesture，可以简化你的代码，且更加可靠。重写 touch 很容易脱离手指；
2. 更新 view.center ，而不是 anchorPoint，除非你非常清楚你在做什么
3. 最好不要在 view 自己的 touch 方法中再更新自己的 center，相对位置容易问题，应该再加个容器 view

**Comment by Hoony-HU** [comment]
好吧 
我现在是在appear里边调用一次check 来解决问题
至于Pan： 我的需求是没法满足 
对于修改anchorPoint：是为了让拖拽看起来正常点 不会再拖拽刚开始的时候出现一个闪现的变化而是从我的手指拖动开始移动 当然你也可以使用相对offset来实现同样的事情，这只是我比较偏好的手法
