### ISSUE TITLE
UIToolbar 显示和影藏出现位置偏差

### ISSUE THREAD

**Issue by teng555teng** [rickytan/RTRootNavigationController#2]
UIToolbar 显示和影藏出现位置偏差

**Comment by rickytan** [comment]
有截图吗？

**Comment by teng555teng** [comment]
![simulator screen shot jul 7 2016 11 07 48 am](https://cloud.githubusercontent.com/assets/4971709/16641449/37d30626-4433-11e6-9f62-4d52a7ff793f.png)

**Comment by teng555teng** [comment]
UIToolbar 会遮住 tableview 导致tableview显示不全

**Comment by teng555teng** [comment]
vc.edgesForExtendedLayout = UIRectEdgeTop | UIRectEdgeLeft | UIRectEdgeRight;
我暂时用这种方法解决

**Comment by teng555teng** [comment]
self.navigationController.navigationBar.translucent = YES; 会出现

**Comment by rickytan** [comment]
你的 toolbar 是自己加的还是 navigation 自带的？

**Comment by rickytan** [comment]
你这其实是个自定义的 tabbar controller 吧，系统的应该不会有问题，自定义的需要自己处理
