### ISSUE TITLE
测试发现popToViewController: animated:方法无法返回到某个controller，麻烦检查一下

### ISSUE THREAD

**Issue by userdefault** [rickytan/RTRootNavigationController#20]

**Comment by userdefault** [comment]
已结局:[self.navigationController popToViewController:self.rt_navigationController.rt_viewControllers[0] animated:YES];

**Comment by rickytan** [comment]
这个不是解决办法。能提供下你的层级结构及调用代码吗？

**Comment by userdefault** [comment]
@rickytan 我写的demo，控制器A push到B，B push到C，然后C返回B后者A，测试发现直接使用[self.navigationController popToViewController:controllerB animated:YES]方法不行，你看下

**Comment by rickytan** [comment]
你在 **C** 里返回到 **B**，只有一层，直接 `popViewControllerAnimated:` 不就好了么？

一定要 `popToViewController:animated:`，你的 **B** 实例是怎么获取的？

**Comment by userdefault** [comment]
@rickytan ，我是整体测试下你的方法，因为popToViewController:animated:在真实项目中会经常用，我是storyboard创建的控制器，获取的方法也是根据控制器id取的方法

**Comment by rickytan** [comment]
通过 **storyboard** 的 **ID** 每次会创建新的实例，并不是你之前 push 进去的 **B**

**Comment by userdefault** [comment]
@rickytan 用storyboard都是根据id来取控制器啊

**Comment by rickytan** [comment]
**Discussion**
You use this method to create view controller objects that you want to manipulate and present programmatically in your application. Before you can use this method to retrieve a view controller, you must explicitly tag it with an appropriate identifier string in Interface Builder.

This method creates a new instance of the specified view controller each time you call it.
