### ISSUE TITLE
好像和WMPageController会有冲突，侧滑禁止无效。

### ISSUE THREAD

**Issue by octsama** [rickytan/RTRootNavigationController#201]
层级结构我简单描述一下。
```
├── UITabBarController
│   ├── RTRootNavigationController
│   │   ├──UIViewController                     1
│   │   │   ├──WMPageController           2
│   │   │   │   ├──WMScrollView           3
│   │   │   │   │   ├──UIViewController 4
│   │   │   │   │   ├──UIViewController
│   │   │   │   │   ├──UIViewController
```
无论在WMPageController还是里面的UIViewController设置rt_disableInteractivePop = YES都还是可以侧滑的。

**Comment by loveKM** [comment]
我也遇到这个问题了，写在哪里都不好使

**Comment by loveKM** [comment]
怎么解决呀

**Comment by rickytan** [comment]
demo 程序发一个？

**Comment by loveKM** [comment]
我解决了，我本地有一个UINavigationController+FDFullscreenPopGesture类，把它去掉了就好使了，但是我记得我没有引用这个文件呀，非得删除了才可以，这是为啥呢

**Comment by rickytan** [comment]
它应该也编译进去了，看看 `+ load` 方法，有没有 swizzle

**Comment by octsama** [comment]
我也解决了，你一说swizzle我就查了一遍，果然有个第三方框架里面有个UINavigationController的分类，里面他用了swizzle用一个自定义的全屏滑动返回接替了系统的。
