### ISSUE TITLE
关于禁用滑动返回

### ISSUE THREAD

**Issue by luxiaol** [rickytan/RTRootNavigationController#202]
请问为什么不直接使用navigationController.interactivePopGestureRecognizer.enabled 来设置是否禁用滑动返回而是使用navigationController.rt_disableInteractivePop 来设置？
如果项目使用了这个这个导航栏，同时接入了其他三方sdk的业务，类似于支付宝里面可以使用ofo的sdk。此时如果三方sdk要禁掉滑动返回的话， 在项目导航结构的情况下是无法尽调的，这个时候就比较难搞了。

**Comment by rickytan** [comment]
只是为了把一个全局变量改为局部变量，每个 vc 管好自己就好，而不需要记住上一次的设置，当 vc 消失时还原设置。iOS 系统中类似的改动的 statusBar 的颜色控制等。

**Comment by luxiaol** [comment]
既然每个VC都有单独的NavigationController，那navigationController.interactivePopGestureRecognizer 从某种意义上来说也就不是全局变量了吧？ 这没办法解决集成三方业务时，三方业务在不知道当前导航栏结构的情况下禁掉滑动返回的问题

**Comment by rickytan** [comment]
每个 vc 的单独 navigationController 只提供 navigationBar，并不用作层级管理，所有的 push & pop 操作转发给了再上一级的 navigationController，即 **self.rt_navigationController**。所以 开关 **navigationController. interactivePopGestureRecognizer** 没有用的，需要  **self.rt_navigationController. interactivePopGestureRecognizer**，而这个是全局一个的

**Comment by luxiaol** [comment]
原来如此。
那请教下我之前描述的那种情况怎么办。感觉只有让三方sdk去依赖这个导航栏了

**Comment by YanshuangyingDarker** [comment]
怎么在当前页面禁用滑动返回手势？

**Comment by rickytan** [comment]
```objc
- (void)viewDidLoad {
    self.rt_disableInteractivePop = YES;
```

**Comment by MQL9011** [comment]
很有用 感谢作者的解答
