### ISSUE TITLE
iOS11 push 到二级页面crash

### ISSUE THREAD

**Issue by onceMu** [rickytan/RTRootNavigationController#208]
iOS 11 push 到二级页面闪退。
在一级页面的时候，在debug中 打开 view debugging - show view frames。
然后再push 到二级页面就会crash。
错误信息是 UIKit中的assert 信息。
*** Assertion failure in -[UIVisualEffectView _addSubview:positioned:relativeTo:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3698.52.10/UIVisualEffectView.m:1558
具体代码是
self.containerNavigationController.view.autoresizingMask = UIViewAutoresizingFlexibleHeight | UIViewAutoresizingFlexibleWidth;

这个时候 NSLog，P 都无法打印 self.containerNavigationController.view 属性。

补充一下：
这个时候打印self.contentViewController.view 也是同样的错误。

**Comment by onceMu** [comment]
经过测试，即使是最简单的demo，在debug中 打开 view debugging - show view frames 中都会crash。

**Comment by rickytan** [comment]
你 Xcode 什么版本？

**Comment by onceMu** [comment]
9.4和9.3.
我通过 bugly 收集的线上闪退信息，分析之后，也会指向上述的函数crash。

**Comment by rickytan** [comment]
iOS 11.4 吗？

**Comment by onceMu** [comment]
iOS 11.3.1

**Comment by rickytan** [comment]
貌似无法复现。你有安装什么 Xcode 插件吗？

**Comment by onceMu** [comment]
没有特别的插件。我现在简单的demo貌似也不能复现了，但是主工程还是可以复现这个问题。

**Comment by onceMu** [comment]
![2018-06-04 5 45 04](https://user-images.githubusercontent.com/3349775/40910584-17114b16-681f-11e8-8a0b-6c2ff7d361be.png)

**Comment by rickytan** [comment]
![image](https://user-images.githubusercontent.com/1250207/40949252-bc0cf914-689f-11e8-8fcd-6af5facd75d9.png)
看起来很像是这里引起的

**Comment by onceMu** [comment]
可能是别的问题导致的连锁反应。
非常感谢。
