### ISSUE TITLE
为什么设置self.navigationController.navigationBar.translucent = NO之后切换效果很不好？

### ISSUE THREAD

**Issue by HZRZCW** [rickytan/RTRootNavigationController#211]
很多项目中self.navigationController.navigationBar.translucent = NO都要这样设置的。

**Comment by rickytan** [comment]
有截屏吗？

**Comment by HZRZCW** [comment]
![gif](https://user-images.githubusercontent.com/12219811/42668287-69d931a2-8682-11e8-973e-87a21915d222.gif)

**Comment by HZRZCW** [comment]
![image](https://user-images.githubusercontent.com/12219811/42668338-ab3a1742-8682-11e8-8c4e-e308ef07f1cc.png)

**Comment by rickytan** [comment]
因那个是自定义的 NavigationBar，你换成系统的应该好了，毛玻璃效果
