### ISSUE TITLE
不支持UIViewControllerAnimatedTransitioning自定义转场

### ISSUE THREAD

**Issue by zengguorui** [rickytan/RTRootNavigationController#215]
在使用过程中发现该导航不支持UIViewControllerAnimatedTransitioning自定义转场动画，应该是每个控制器都有独立的导航造成的。不知道怎么改修。

**Comment by zengguorui** [comment]
解决方法，把获取到的控制器用下面方法转换下就可以出现转场动画，但是次级界面导航消失了。orz
UIViewController *fromVC = [transitionContext viewControllerForKey:UITransitionContextFromViewControllerKey];
    fromVC = ((RTContainerController *)fromVC).contentViewController

**Comment by zengguorui** [comment]
找到原因了，这里不要强转，使用的时候直接用
((RTContainerController *)fromVC).contentViewController
来代替fromVC就可以了。

**Comment by rickytan** [comment]
嗯，可以参考 demo ，有自定义转场的，你的 vc 被包了一层
