### ISSUE TITLE
诸多uiviewcontoller的方法不能用

### ISSUE THREAD

**Issue by a83988029** [rickytan/RTRootNavigationController#216]
需要实现一个功能，但是发现vc里面的viewwillDisappear，viewdidappear, viewdiddisappear都不会调。
说好的不改变系统的调用方式的呢

**Comment by rickytan** [comment]
目前唯一会影响的是 `- willMoveToParentViewController` 和 `- didMoveToParentViewController`，因为确实时机不一样了
