### ISSUE TITLE
xcode10 libstdc++  问题如何解决呢？

### ISSUE THREAD

**Issue by LeeShiYoung** [rickytan/RTRootNavigationController#219]

**Comment by faimin** [comment]
在提 `issue` 之前能不能先自己尝试解决一下？！网上搜一下一大堆相关问题的帖子，比如 [`libstdc++适配Xcode10与iOS12`](https://awhisper.github.io/2018/06/08/libstdc-inxcode10ios12/)。自己搜索的速度绝对比在这里提`issue`等待作者回复的速度要效率很多倍。 
而且你提的这个问题好像和这个库没有任何关系吧。
