### ISSUE TITLE
有一个疑问，为什么推荐使用customBackItemWithTarget来设置backItem，而不是使用系统的呢？useSystemBackBarButtonItem

### ISSUE THREAD

**Issue by songhailiang** [rickytan/RTRootNavigationController#22]
主要是考虑了哪些方面的因素呢？
还望能指点一下，感谢！

**Comment by rickytan** [comment]
为了让系统的出来，我在每个 **VC** 前 push 了一个空的 **VC**，使得真正的 **VC** 是导航器的第二个 **VC**，这样会产生较高的内存占用，代码中我也[注释](https://github.com/rickytan/RTRootNavigationController/blob/master/RTRootNavigationController/Classes/RTRootNavigationController.h#L61)了

**Comment by songhailiang** [comment]
嗯，我看到了那个注释，只是说了会占用更多的内存，但是没有解释是为什么，所以才有的这个疑问。谢谢您的指点。
昨天把这个框架集成到了现有的已完成的项目中了，改动非常小，非常赞！
唯一要注意的就是在使用self.navigationController.viewControllers时要替换成self.rt_navigationController.rt_viewControllers，建议您能把文档再细化一点，能让人更容易上手。
