### ISSUE TITLE
关于导航栏异常出现渐变色bug

### ISSUE THREAD

**Issue by iBinbro** [rickytan/RTRootNavigationController#220]
详细的测试工程我已经上传到git，我的手机是iOS12，麻烦看下 谢谢
https://github.com/iBinbro/RTRootNavigationControllerTest.git

你好，在对导航控制器 重新设置 viewcontrollers 之后，会导致透明色的导航栏出现浅白色
```objective-c
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(5 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        NSMutableArray *vcTempsAryM = [self.rt_navigationController.rt_viewControllers mutableCopy];
        [self.rt_navigationController setViewControllers:vcTempsAryM];
    });
```
导航栏设置
```objc
- (void)setNav {
    self.navigationController.navigationBar.barTintColor = [UIColor clearColor];
    self.navigationController.navigationBar.tintColor = [UIColor clearColor];
    [self.navigationController.navigationBar setShadowImage:[UIColor imageWithColor:[UIColor clearColor]]];  //导航栏分割线
    [self.navigationController.navigationBar setBackgroundImage:[UIColor imageWithColor:[UIColor clearColor]] forBarMetrics:UIBarMetricsDefault];  //导航栏背景图片
}
```
详细的测试工程我已经上传到git，我的手机是iOS12，麻烦看下 谢谢
https://github.com/iBinbro/RTRootNavigationControllerTest.git

**Comment by rickytan** [comment]
为什么要重新设置一样的实例？只在 `iOS 12` 上出现吗？

**Comment by iBinbro** [comment]
> 为什么要重新设置一样的实例？只在 `iOS 12` 上出现吗？

目前仅在iOS12上测了下，其他版本没测过，设置不同的实例也是一样的，具体需求是把topviewcontroller移除，然后push上新的viewcontroller，所以用的setviewcontroller...，然后返回上个页面看到导航栏浅白色。导致了之前的vc透明色的导航栏出现莫名的浅白色，如果不是透明色是没问题的 麻烦看下 谢谢

**Comment by rickytan** [comment]
你的工程文件不完整，无法打开

**Comment by iBinbro** [comment]
> 你的工程文件不完整，无法打开

更新了下 可以打开了 麻烦看下

**Comment by Xianyus** [comment]
ios12 同样的问题

**Comment by iBinbro** [comment]
> 你的工程文件不完整，无法打开

你好 有复现 浅白的现象吗？

**Comment by rickytan** [comment]
嗯，是有的，你这种用法，应该在所有系统上都会有。原因在于你的 `TestViewController` 的 `view` 已经 load 了，再重新设置到 navigationController 中，它会自动为你包一层 `RTContainerNavigationController`，但此时 `TestViewController` 的 `- viewDidLoad` 不会再进入，所以 `UINavigationBar` 是默认样式，即泛白的。

修复方法 3 种：
1. 你的 `- setNav` 方法放到 `- viewWillAppear:` 中
    ```objc
    - (void)viewWillAppear:(BOOL)animated
    {
        [super viewWillAppear:animated];
        [self setNav];
    }
    ```
2. `- setViewControllers:` 用新实例：
    ```objc
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(5 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [self.rt_navigationController setViewControllers:@[[TestViewController new]]];
    });
    ```
3. 使用 **UIAppearance** 来设置全局样式

**Comment by SummerHH** [comment]
为什么隐藏导航栏之后，侧滑功能就失效了，建议作者暴露个属性出来

**Comment by rickytan** [comment]
与系统原生行为保持一致。你可以手动指定 `self.rt_disableInteractivePop = NO`
