### ISSUE TITLE
每次运行都有断点在RTRootNavigationController.m 第418  [self.view layoutIfNeeded]; 

### ISSUE THREAD

**Issue by Goallying** [rickytan/RTRootNavigationController#221]
每次运行都有断点在RTRootNavigationController.m 第418  [self.view layoutIfNeeded];

**Comment by rickytan** [comment]
这种应该是你断点设置的问题，删除所有断点再试试：
![image](https://user-images.githubusercontent.com/1250207/45912419-7d62f380-be53-11e8-8be4-8211f99aeca7.png)
