### ISSUE TITLE
你好 确认个问题

### ISSUE THREAD

**Issue by iBinbro** [rickytan/RTRootNavigationController#223]
关于scrollview 内边距自适应，
如果我通过rtnav设置了
[self.navigationController.navigationBar setBackgroundImage:[UIImage imageNamed:@"placeholder"] forBarMetrics:UIBarMetricsDefault]; 
这样被push的VC的view会下移到navbar的下面，而scrollview其实也就不需要做内边距适配了
所以scrollview的顶部问题其实不需要做适配了，对吧？

**Comment by rickytan** [comment]
这个取决于你的 `navigationBar` 是否为 `translucent`，以及你的图片是否是透明的。其实你自己用视图查看器看下就好
