### ISSUE TITLE
iOS12 下 导航栏在viewwillDidAppear的时候才显示

### ISSUE THREAD

**Issue by WXXXXH** [rickytan/RTRootNavigationController#224]
viewwillDidAppear 之前 所有的navBar.subViews 都是空的

**Comment by rickytan** [comment]
可能重复了 #222

**Comment by WXXXXH** [comment]
> 可能重复了 #222
这个能解决吗？和222 是不一样的啊，iOS12 之前，在viewWillAppear的时候 navBar的子视图就有了，可是在iOS12 的时候只有在viewwillDidAppear 才有，现在根本没办法操作这里面的属性，操作的时候都显示了

**Comment by seanLee** [comment]
我也遇到同样的问题了 我觉得也不算重复吧.我现在是想在```viewDidLoad```方法里面获取navigationBar的层级来操作.然后我这边试了一下,在```viewDidLayoutSubviews```这个方法里面navigationBar的subviews也为空,但是在```viewwillDidAppear```方法的话,效果也不是很好.

**Comment by WXXXXH** [comment]
> 可能重复了 #222

那个是约束没完成导致的frame不一致，这个是在viewwillDidAppear之前 navBar 的子视图都没有初始化，根本没办法操作里面的视图，必然隐藏某一个视图啥的，在ios12之前都是可以显示的，只有ios12不行

**Comment by WXXXXH** [comment]
> 可能重复了 #222

大佬 几时能解决啊，或者有什么临时性的方案，让navBar自视图马上显示出来

**Comment by rickytan** [comment]
先强制  layout 一下试试？

**Comment by seanLee** [comment]
> 先强制 layout 一下试试？

我试了一下.```layoutSubviews```如果你是说得这个方法,那还是不行

**Comment by rickytan** [comment]
```objc
[navBar setNeedsLayout];
[navBar layoutIfNeeded];
```

**Comment by WXXXXH** [comment]
早前我是这样弄的 不行 是这个时候还没有子视图 所以没有效果

发自我的 iPhone

在 2018年10月8日，19:50，Ricky Tan <notifications@github.com<mailto:notifications@github.com>> 写道：


[navBar setNeedsLayout];
[navBar layoutIfNeeded];

**Comment by wangshaoren** [comment]
viewwillDidAppear 之前 所有的navBar.subViews 都是空的，请问一下这个问题有解决方案了吗？

**Comment by LuKane** [comment]
请问现在 OK了吗!?

**Comment by WXXXXH** [comment]
不OK 换了其他解决方案

发自我的 iPhone

在 2018年10月15日，17:07，LuKane <notifications@github.com<mailto:notifications@github.com>> 写道：


请问现在 OK了吗!?

**Comment by LuKane** [comment]
请问 如何解决的!!! 求告知, 能留下联系方式吗?

**Comment by LuKane** [comment]
@WXXXXH 请求是换了什么解决方案!?

**Comment by WXXXXH** [comment]
把系统的隐藏了 自己写了个假的 就一个页面

发自我的 iPhone

在 2018年10月16日，14:50，LuKane <notifications@github.com<mailto:notifications@github.com>> 写道：


@WXXXXH<https://github.com/WXXXXH> 请求是换了什么解决方案!?

**Comment by seanLee** [comment]
@rickytan 我这边断点了一下.在```RTRootNavigationController.m```文件里第```421```行的代码```[self.view layoutIfNeeded];```会导致提前执行ViewController的```ViewDidLoad```方法调用,我尝试去掉这行代码,然后生命周期就正常,但是我不确定这行代码的作用.

**Comment by rickytan** [comment]
**VC** 的生命周期本身是正常的，加这一行只是提前了 `viewDidLoad`，但次序是对的。之前为了 fix 一个 issue

**Comment by seanLee** [comment]
但是现在的问题就是这行代码导致的.Navigation调用self.view导致VC调用了self.view,然后造成V```viewDidLoad```提前调用.

**Comment by onceMu** [comment]
断点调试，发现在viewDidLayoutSubviews 中拿到的contentViewController的navigationbar subviews不为空，所以我把操作放在了viewDidLayoutSubviews和 viewWillLayoutSubviews中。

**Comment by seanLee** [comment]
@rickytan  好的

**Comment by WXXXXH** [comment]
修复了吗？

发自我的 iPhone

在 2018年10月25日，14:21，Ricky Tan <notifications@github.com<mailto:notifications@github.com>> 写道：


@wangshaoren<https://github.com/wangshaoren> @seanLee<https://github.com/seanLee> 有空帮忙测试下分支 fix/issue224 有没有 fix 你的问题；

pod 'RTRootNavigationController', :git => 'https://github.com/rickytan/RTRootNavigationController', :branch => 'fix/issue224'

**Comment by seanLee** [comment]
我这边验证暂时没有发现其他问题～
