### ISSUE TITLE
设置透明度为NO后和真实颜色有色差

### ISSUE THREAD

**Issue by BigH2OB** [rickytan/RTRootNavigationController#225]
//去除分割线
    
    [self.navigationController.navigationBar setShadowImage:[UIImage new]];
    [self.navigationController.navigationBar setBackgroundImage:[UIImage new] forBarMetrics:UIBarMetricsDefault];
    //不透明
     self.navigationController.navigationBar.translucent = NO;
    //设置背景色
     self.navigationController.navigationBar.barTintColor = [UIColor colorWithHexString:@"1DC69B"];

这么设置之后,导航栏背景和真实颜色还是不一致

**Comment by rickytan** [comment]
`barTintColor` **tint** 本意就是泛白的，这是系统的效果。要颜色完全一样，用 `UIColor` 生成一张一像素的可拉伸图，作为背景图。
```objc
[self.navigationController.navigationBar setBackgroundImage:[UIImage imageWithColor:xxx]  // 需要你自己实现
                                                                                forBarMetrics:UIBarMetricsDefault];
```

**Comment by rickytan** [comment]
你的实现代码贴一下
