### ISSUE TITLE
0.7，bug太多

### ISSUE THREAD

**Issue by VillageMud** [rickytan/RTRootNavigationController#230]

**Comment by rickytan** [comment]
请给个截图，或者代码

**Comment by VillageMud** [comment]
![image](https://user-images.githubusercontent.com/12798195/47976641-4e949a00-e0ee-11e8-9d7f-ee38298236f6.png)
![image](https://user-images.githubusercontent.com/12798195/47976648-58b69880-e0ee-11e8-8a0f-d81ea7c29831.png)
这是第一种情况

**Comment by VillageMud** [comment]
![image](https://user-images.githubusercontent.com/12798195/47977105-4c800a80-e0f1-11e8-96ba-1c2965962ded.png)
![image](https://user-images.githubusercontent.com/12798195/47977110-530e8200-e0f1-11e8-826f-1e28a390e5bf.png)
![image](https://user-images.githubusercontent.com/12798195/47977121-5bff5380-e0f1-11e8-9d30-79f1f93e7896.png)
![image](https://user-images.githubusercontent.com/12798195/47977126-64f02500-e0f1-11e8-8fc6-ced1848e4574.png)
push后，点击back按钮返回到主页面，底部的tabbar按钮的问题，会进行闪动下，和原来的位置有偏移，从上又回到原始位置，很明显

**Comment by VillageMud** [comment]
另外设置，navi.useSystemBackBarButtonItem = YES;后，在主页面进入到第二级页面，返回按钮还是系统的<back，只有从第二级页面进入到第三级界面的时候，才会出现返回按钮为，<首页这种样式的

**Comment by smalldu** [comment]
同样的问题，怎么解决。好像只在iOS 12.1 iPhone X出现。

**Comment by smalldu** [comment]
@VillageMud  这个有可能跟我遇到问题一样是iOS 12.1的问题 
参考：
https://github.com/QMUI/QMUI_iOS/issues/410

**Comment by VillageMud** [comment]
对的，这个只有在iOS12.1才会出现，使用系统原生的，我这边却没有这个问题

**Comment by rickytan** [comment]
0.7.0 版目前问题比较多，最近也没空解决。建议还是先撤回 0.6.x

**Comment by VillageMud** [comment]
已经退回，0.6.7.到时候进行通知下

**Comment by rickytan** [comment]
@VillageMud  在情况一下，只有一个导航器，第一个 **VC** 其实是 TabBarController，它没有标题，所以默认为 `Back`，于是出现二级 push 到三级才有正确的返回标题，一级到二级都是 `Back`。
情况二下，目前不清楚原因，一个可行的方案是设置 TabBar 为不透明：
```objc
tabController.tabBar.translucent = NO;
```

**Comment by rickytan** [comment]
如果你只有一级页面有 TabBar ，建设改为情况一的集成方式

**Comment by rickytan** [comment]
`hotfix/0.7.0` 分支可以测试一下 @VillageMud

**Comment by VillageMud** [comment]
@rickytan 我看了下，网易云音乐，4.3.5版本的，他们这个是没有出现这个问题的，tabBar.translucent = yes，目前咱们这个解决方案个人认为这是暂时情况的，不知道，大大和网易云音乐那边的同学可以做下交流部，😝，个人意见

**Comment by rickytan** [comment]
嗯，我现在就在，跟自己交流就好:joy:。云音乐现在已经到 5.7.0 版了，你的 4.x.x 也太老了吧。另外，那个  tabBar 按钮是假的，因为要实现换肤功能
