### ISSUE TITLE
通过self.navigationController.tabBarController获取到的tabBarController会是nil

### ISSUE THREAD

**Issue by 577528249** [rickytan/RTRootNavigationController#231]
你好，使用RTRootNavigationController创建出来的navigationController，即便tabBarController存在，获取tabBarController属性时会是nil，因为在RTRootNavigationController.m中重写- (UITabBarController *)tabBarController方法，我想知道重写的这个方法的里面的判断依据是什么？是为了解决什么bug吗？

 ```
 - (UITabBarController *)tabBarController
{
    UITabBarController *tabController = [super tabBarController];
    RTRootNavigationController *navigationController = self.rt_navigationController;
    if (tabController) {
        if (navigationController.tabBarController != tabController) {   // Tab is child of Root VC
            return tabController;
        }
        else {
            return !tabController.tabBar.isTranslucent || [navigationController.rt_viewControllers rt_any:^BOOL(__kindof UIViewController *obj) {
                return obj.hidesBottomBarWhenPushed;
            }] ? nil : tabController;
        }
    }
    return nil;
} 
```

**Comment by rickytan** [comment]
时间比较久远了，应该是为了解决从 有 tab bar push 到无 tab bar （`hidesBottomBarWhenPushed = YES`）时的 bottom insets 问题。你是通过  `self.navigationController.tabBarController` 获取的吗？改为 `self.tabBarController` 试试呢？

**Comment by 577528249** [comment]
通过self.navigationController.tabBarController会走你重写的方法，tabBar.isTranslucent时会是nil，用self.tabBarController可以获取到，谢谢了

**Comment by rickytan** [comment]
其实你用原生的 `UINavigationController` 也应该用 `self.tabBarController` 来获取，开发者一般情况下不需要感知此项目的存在
