### ISSUE TITLE
在首次push时添加的左上角返回按钮不生效

### ISSUE THREAD

**Issue by SabinLee** [rickytan/RTRootNavigationController#233]
我有一个自定义导航控制器继承自RTRootNavigationController, 现在我的需求是导航控制器initWithRootVC后左上角自动加一个返回按钮, 我在我继承的这个vc是这样写的
```objc
-(void)pushViewController:(UIViewController *)viewController animated:(BOOL)animated{
    // 当push这个子控制器时, 隐藏底部的工具条
    if (self.viewControllers.count > 0) {
        viewController.hidesBottomBarWhenPushed = true;
        viewController.rt_disableInteractivePop = NO;
    }
    UIButton *backButton = [[UIButton alloc] initWithFrame:CGRectMake(0, 0, 30, 40)];
    UIImageView *bgImg = [[UIImageView alloc] initWithFrame:CGRectMake(0, 10, 11, 20)];
    bgImg.image = [UIImage imageNamed:@"img_back_orange"];
    [backButton addSubview:bgImg];
    [backButton addTarget:self action:@selector(back) forControlEvents:UIControlEventTouchUpInside];
    viewController.navigationItem.leftBarButtonItem = [[UIBarButtonItem alloc] initWithCustomView:backButton];
    // 将viewController压入栈中
    [super pushViewController:viewController animated:animated];
}
```
但是左上角返回按钮没加上, 我看了一下, super里面是有个判断, 难道我就不能在navVC初始化并首次push的时候给vc添加返回吗?

**Comment by rickytan** [comment]
在你的 vc 中重写 rt_customBackBarButtonItem 方法就好，不需要继承此类。

> 另外，使用 0.6.x 版，0.7 目前有问题

**Comment by SabinLee** [comment]
> rt_customBackBarButtonItem

您好! 我现在在tabbar控制器初始化时不使用我继承的导航vc, 而直接使用RTRootNavVC,  在个人中心首页使用rt_customBackBarButtonItem 仍然不起作用, 但是在个人中心点击push后的页面就生效, 也就是栈底控制器总是不生效, 这是为什么呢?
相关代码如下:
//初始化tabbarVC
[tabbarVC addChildViewControllerWithChildVC:[[RTRootNavigationController alloc] initWithRootViewController:[[PersonalViewController alloc] init]] title:@"我的" normalImage:@"personal_normal" selectedImage:@"personal_selected"];

//PersonalViewController内部: (实现方法, 左上角无按钮)
-(UIBarButtonItem *)rt_customBackItemWithTarget:(id)target action:(SEL)action{
    UIButton *btn = [[UIButton alloc] initWithFrame:CGRectMake(0, 0, 40, 40)];
    btn.backgroundColor = [UIColor redColor];
    return [[UIBarButtonItem alloc] initWithCustomView:btn];
}

//PersonalViewController内, [self.navvc pushvc1], vc1内实现方法, 左上角有红色按钮

**Comment by SabinLee** [comment]
> 在你的 vc 中重写 rt_customBackBarButtonItem 方法就好，不需要继承此类。
> 
> > 另外，使用 0.6.x 版，0.7 目前有问题

麻烦回复一下, 谢谢了

**Comment by SabinLee** [comment]
@rickytan 能看见我的@吗?

**Comment by rickytan** [comment]
`addChildViewControllerWithChildVC:` 这个方法你自己的？使用 
```objc
tabbarVC.viewControllers = @[vc];
```

**Comment by SabinLee** [comment]
> `addChildViewControllerWithChildVC:` 这个方法你自己的？使用
> 
> ```objc
> tabbarVC.viewControllers = @[vc];
> ```

经测试, 也不能用, 您可以自己尝试在tabbarVc+navVc这种模式下对navVc第一次push进来的vc加一个自定义返回,  我这边一直是加不上的, 现在的6.7和之前的7.0版本都加不上

**Comment by rickytan** [comment]
demo 程序跑起来没问题吧，对比下吧。没有你的代码只能盲猜

**Comment by SabinLee** [comment]
> demo 程序跑起来没问题吧，对比下吧。没有你的代码只能盲猜

demo是没问题的, 而且demo里面也没有这种尝试.
所以我一直在问的两个问题就是
1.如何给栈底控制器加自定义返回按钮?(我只有一个可行的方法, 在上面的截图)
2.如何统一管理这个返回按钮, 比如我每次push进去就设置一个默认的自定义返回按钮(我现在是用继承, 拦截push)
能回答我一下吗

**Comment by SabinLee** [comment]
> 第一个问题，你指的是 navigation 中的第一个 **VC** ？它为什么要加返回按钮？这种情况你只能自己设置一个 leftBarButtonItem
> 第二个问题，在 `UIViewController` 的任何 **category** 中实现 `rt_customBackBarButtonItem` 方法即可。你这里不生效的话，放个 demo 上来，感觉是层级关系或者使用方式不太对

OK, 没有其他问题了,感谢指教!
