### ISSUE TITLE
怎么统一设置导航栏样式呢?

### ISSUE THREAD

**Issue by SabinLee** [rickytan/RTRootNavigationController#238]
例如我大多数情况下是白色导航栏, 有几个是黑色和透明, 那么有没有推荐的做法来统一设置默认为白色导航栏?
1,继承自某个基类, 在基类写个方法setNavStyle, 在viewDidLoad默认调用它?
2,分类的话要用方法交换拦截viewDidLoad, 并调用setNavStyle
3,继承框架的navVC, 拦截push并执行[vc setNavStyle], 但是第一次push时设置不生效

**Comment by rickytan** [comment]
三种方式都可以：
1. 使用系统的 **UIAppearence** 接口
2. 设置 RTRootNavigationController 的 navigationBar 样式，然后设置 transferNavigataionAppearence = YES
3. 所有 VC 继承自一个你项目的公共子类，如：YourBaseViewController，在 `- viewDidLoad` 中设置
