### ISSUE TITLE
push 到新界面的时候，tabBar为什么没有隐藏？？？

### ISSUE THREAD

**Issue by zhangqi02060227m** [rickytan/RTRootNavigationController#239]
自定义的tabBarController  继承于 UITabBarcontroller， push到新界面的时候，tabbar没有隐藏。。。

**Comment by rickytan** [comment]
有两种集成方式。一种是只有 root 上有 tabBar，二级页面都自动没有；一种是二级页面可以有，也可以通过 .hideBottomBarWhenPushed = YES 设置为没有。具体见 demo 程序中的  AppDelegate 注释掉的方法
