### ISSUE TITLE
RTRootNavigationController右滑手势和自定义UIScrollView右滑冲突

### ISSUE THREAD

**Issue by easongtd** [rickytan/RTRootNavigationController#24]
我自定义了一个UIScrollView用于图片查看模式，可以左右滚动查看图片。
在这个VC中RTRootNavigationController的右滑无法响应，然后我使用两种方法设置代理来解决都没用，这个问题该怎么解？

方法一：
```
-(BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer
{
    // 首先判断otherGestureRecognizer是不是系统pop手势
    if ([otherGestureRecognizer.view isKindOfClass:NSClassFromString(@"UILayoutContainerView")]) {
        // 再判断系统手势的state是began还是fail，同时判断scrollView的位置是不是正好在最左边
        if (otherGestureRecognizer.state == UIGestureRecognizerStateBegan && self.contentOffset.x == 0) {
            return YES;
        }
    }
    
    return YES;
}
```
方法二：
```
-(BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer
{

    return YES;
}

- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldBeRequiredToFailByGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer {
    if ([otherGestureRecognizer isKindOfClass:[UIScreenEdgePanGestureRecognizer class]]) {
        [gestureRecognizer requireGestureRecognizerToFail:otherGestureRecognizer];
        return NO;
    }
    return YES;
}
```

**Comment by rickytan** [comment]
现有的就可以，只是要边缘

**Comment by easongtd** [comment]
你是说0.5.20这个版本吗，我的是这个版本，不行。我在边缘各个位置都试过了，都直接被scrollView的代理接受掉了

**Comment by rickytan** [comment]
demo 中是的 scroll 的例子的，你有改 scrollview 的什么设置吗？

**Comment by easongtd** [comment]
我这个自定义的UIScrollView是一个第三方的3D图片查看框架，他继承UIScrollView。我自己这里没做任何设置。有哪些设置可能会影响到这个手势冲突？

**Comment by rickytan** [comment]
那个的实现是 `UIScrollView` 中又带 `UIScrollView` 吧？源码地址贴一下，应该是他实现了 gesture 的 delegate 了

**Comment by easongtd** [comment]
https://github.com/jonathantribouharet/JT3DScrollView

**Comment by easongtd** [comment]
如果像你说的又套了一个UIScrollView，那该怎么解？

**Comment by rickytan** [comment]
貌似没有问题啊，看下 [issue24分支](https://github.com/rickytan/RTRootNavigationController/tree/issue24)

**Comment by easongtd** [comment]
这个问题你在issue24分支已解决，但还没合并到master主分支吗？ 我下的是主分支

**Comment by easongtd** [comment]
我刚刚把master和issue24都下过来试过了，在图片模式右滑都不行。这个就放一放了，还有一个问题是全屏右滑后UITableView的左滑删除功能的左滑手势被吃掉了，这要怎么解呢？

**Comment by easongtd** [comment]
我本来已经妥协用侧滑，产品经理说必须全屏右滑，郁闷死

**Comment by rickytan** [comment]
issue24 和 master 代码是一样的，只是加了个 demo

**Comment by rickytan** [comment]
可以 `UIGesture` 的 `delegate` 中返回 `NO`，`shouldBegin` 那个方法，判断用户是向左还是向右

**Comment by easongtd** [comment]
恩，可以的兄弟，谢了。今天有空把方法贴出来：
- (BOOL)gestureRecognizerShouldBegin:(UIPanGestureRecognizer *)gestureRecognizer {
    //只有非根控制器才有滑动返回功能，根控制器没有，判断导航控制器是否只有一个子控制器
    if (self.childViewControllers.count == 1) {
        //如果在根控制器，就不需要触发滑动手势
        return NO;
    }
    
    //处理左滑事件
    CGPoint translation = [gestureRecognizer translationInView:gestureRecognizer.view];
    if (translation.x <= 0) {
        return NO;
    }
    
    return YES;
}
