### ISSUE TITLE
统一设置返回按钮的样式问题

### ISSUE THREAD

**Issue by yanashenyang** [rickytan/RTRootNavigationController#244]
你这设置返回按钮的样式，可以暴露个接口吗。现在我们项目的vc都是继承自uiviewcontroller，要替换统一的返回按钮样式的话，新建个基类不友好。如果重写pushViewController后，在里面设置返回按钮，则会与返回手势逻辑冲突，导致每个页面的返回手势失效

**Comment by rickytan** [comment]
不用基类继承，用分类（Category）即可实现

**Comment by harveyseeking** [comment]
使用分类那每个页面也都要调用一次

**Comment by rickytan** [comment]
实现方法即可，自动的

**Comment by rickytan** [comment]
实现方法即可，自动的
