### ISSUE TITLE
如何设置导航leftItems？

### ISSUE THREAD

**Issue by DragonMichael** [rickytan/RTRootNavigationController#246]
![image](https://user-images.githubusercontent.com/20676401/54813753-34d4a780-4cc9-11e9-9775-1244e5d19feb.png)
代码如图两个都设置 不显示 导航右边按钮

**Comment by DragonMichael** [comment]
ios12 模拟器 不显示导航按钮 使用[self.navigationItem setRightBarButtonItems:@[self.navRightItem]]; 数组设置， [self.navigationItem setRightBarButtonItem:self.navRightItem];单独设置 显示

**Comment by DragonMichael** [comment]
如果左侧想 显示返回 和 其他按钮 如何设置 ？ 麻烦大佬了

**Comment by rickytan** [comment]
本项目利用 leftBarButtonItem 作为返回按钮，所以要同时显示返回和左按钮，需要开发者自己做一些事情：
```objc
- (void)viewDidLoad {
   ...
   self.navigationItem.leftBarButtonItems = @[self.navigationItem.leftBarButtonItem,  yourLeftItem0, yourLeftItem1];
}
```

**Comment by DragonMichael** [comment]
你好 第一个问题 使用数组设置不显示右边按钮 大佬了解吗 iOS 12 模拟器， 如果右边想设置两个按钮就不行了

**Comment by rickytan** [comment]
你自定的 item 需要先 sizeToFit 调整一下大小，否则可能是 {0, 0}

**Comment by DragonMichael** [comment]
好的 我试试
