### ISSUE TITLE
返回与侧滑手势 拦截pop方法 大佬能不能添加个代理？方便拦截使用

### ISSUE THREAD

**Issue by DragonMichael** [rickytan/RTRootNavigationController#248]
RTNavigationItemCustomizable 在这个代理 可以增加个pop 拦截方法 
功能：返回和右滑手势如果该代理被实现 如果代理返回YES, 继续执行；反之NO，停止pop。

**Comment by rickytan** [comment]
有这种需求时，一般直接禁用手势返回了吧

**Comment by DragonMichael** [comment]
需求是 点击返回 要弹个提示窗 提示用户 是否放弃更改 这样的

**Comment by DragonMichael** [comment]
我现在是拦截 onBack 方法已经实现，只是建议暴露一个代理 免去我写拦截的代码了 😆
