### ISSUE TITLE
实现UINavigationControllerDelegate后，滑动手势失效

### ISSUE THREAD

**Issue by Shannon-Yang** [rickytan/RTRootNavigationController#255]
Hello，请教下NavigationController继承RTRootNavigationController，我需要在UINavigationControllerDelegate中处理我的业务逻辑，在子类NavigationController中实现了UINavigationControllerDelegate后，系统侧滑手势失效，能否有一种好的方式处理？😊

**Comment by rickytan** [comment]
在你不需要处理的 case 中调用  super
