### ISSUE TITLE
self.rt_disableInteractivePop 失效

### ISSUE THREAD

**Issue by orangeren** [rickytan/RTRootNavigationController#256]
[self.navigationController pushViewController:vc animated:NO];
animated为NO的时候，禁止侧滑返回失效；为YES，则没有问题。

**Comment by rickytan** [comment]
什么系统？

**Comment by jifengchao** [comment]
我也发现存在这个问题，

**Comment by jifengchao** [comment]
我也发现这个问题，

**Comment by jifengchao** [comment]
我也发现存在这个问题， RTRootNavigationController是最新的版本，手机系统iOS12.2

**Comment by rickytan** [comment]
#258 fix
