### ISSUE TITLE
在-viewDidLoad 中设置self.rt_disableInteractivePop，出现问题

### ISSUE THREAD

**Issue by jifengchao** [rickytan/RTRootNavigationController#258]
版本：0.7.1
如果上一个页面push到本页面，animated是YES的话，rt_disableInteractivePop设置左滑禁止是有效果的；但是如果animated是NO的话，则rt_disableInteractivePop设置无效

**Comment by rickytan** [comment]
什么时机设置的？

**Comment by jifengchao** [comment]
页面A push 到 页面B 时，在页面B的-viewDidLoad中设置的

**Comment by rickytan** [comment]
确实有问题
