### ISSUE TITLE
在iOS13中设置导航栏返回按钮，会渲染成系统默认颜色是什么问题呢？

### ISSUE THREAD

**Issue by zhangyanlf** [rickytan/RTRootNavigationController#260]

**Comment by rickytan** [comment]
你的图片设置为 Origin 试试？
![image](https://user-images.githubusercontent.com/1250207/66271669-60009c00-e893-11e9-868b-208c33580c0f.png)

**Comment by zhangyanlf** [comment]
ok   设置了显示正常了  谢了
