### ISSUE TITLE
Xcode11-- iOS13。设置导航栏透明无效。

### ISSUE THREAD

**Issue by TML007** [rickytan/RTRootNavigationController#265]
设置如下两个属性没有效果 [self.navigationController.navigationBar setBackgroundImage:[UIImage new] forBarMetrics:UIBarMetricsDefault];
    [self.navigationController.navigationBar setShadowImage:[[UIImage alloc]init]];

**Comment by TML007** [comment]
![Uploading WeChat886a9ec5b4c454caa4e077d7d71bacaf.png…]() 用的是您的demo

**Comment by TML007** [comment]
<img width="992" alt="WeChat886a9ec5b4c454caa4e077d7d71bacaf" src="https://user-images.githubusercontent.com/19261542/67137408-6fa2bc00-f267-11e9-8736-d5f1c40b55a2.png">
用的是您的demo

**Comment by eric1202** [comment]
应该怎么设置呢

**Comment by eric1202** [comment]
> 应该怎么设置呢

    [self.navigationController.navigationBar setBackgroundImage:[UIImage new] forBarMetrics:UIBarMetricsDefault];
    self.navigationController.navigationBar.translucent = YES;
    [self.navigationController.navigationBar setShadowImage:[UIImage new]];
    self.navigationController.navigationBar.backgroundColor = UIColor.clearColor;
