### ISSUE TITLE
A是竖屏，B是横屏竖屏都可以。当A push B后，再横屏，再返回的时候，A的view上面还有一点B的view在上面

### ISSUE THREAD

**Issue by amwujetuu** [rickytan/RTRootNavigationController#27]
A是竖屏，B是横屏竖屏都可以。当A push B后，再横屏，再返回的时候，A的view上面还有一点B的view在上面没有pop完，过了0.2秒才会消失
![aaa](https://cloud.githubusercontent.com/assets/4619350/18470277/6a089dd2-79de-11e6-8d4e-6a1b0640b794.gif)

**Comment by rickytan** [comment]
禁止转屏是如何设置的？我貌似无法重现

**Comment by amwujetuu** [comment]
@rickytan 禁止转屏主要是加了两个类别设置的，如下gif所示，那个设置主要在UIViewController+Extension.m里面

**Comment by amwujetuu** [comment]
@rickytan 禁止转屏主要是加了两个类别设置的，如下gif所示，那个设置主要在UIViewController+Extension.m里面
![aaa](https://cloud.githubusercontent.com/assets/4619350/18496675/574bc742-7a5a-11e6-9925-816280be8dd7.gif)

**Comment by rickytan** [comment]
应该是你的 extension 覆盖了本项目的行为，去掉试试看？

**Comment by amwujetuu** [comment]
@rickytan  去掉后 我怎么设置横竖屏？求方法
