### ISSUE TITLE
关于iOS14的适配工作

### ISSUE THREAD

**Issue by BigPoro** [rickytan/RTRootNavigationController#290]
iOS14的系统导航栏似乎又有变动，状态栏变的更高了。
请问作者会不会持续跟进这些新变化？@rickytan

**Comment by rickytan** [comment]
应该是自动适配的

**Comment by BigPoro** [comment]
> 应该是自动适配的



> 应该是自动适配的

希望如此吧，会少很多的工作量。
感谢大佬的开源。
