### ISSUE TITLE
横竖屏切换出现跟系统UINavigationController不一致的效果

### ISSUE THREAD

**Issue by eryuxinling** [rickytan/RTRootNavigationController#291]
您好，我在使用该库的时候，使一个viewController强制转横屏的时候，当VC已经出来后，才开始转横屏。如果使用系统的UINavigationController，是VC出现的同时转横屏。请问怎么才能做到跟系统一样的效果呢？因为我转屏时有个loading会出现错位。

**Comment by lz11** [comment]
你问题解决了吗

**Comment by rickytan** [comment]
will appear 时机应该太晚了
