### ISSUE TITLE
报错：缺少文件

### ISSUE THREAD

**Issue by mxpasser** [rickytan/RTRootNavigationController#3]
![image](https://cloud.githubusercontent.com/assets/3272620/16224756/0a06df6a-37d6-11e6-9f04-7586946e1f6f.png)
下载zip解压后，Run的时候报了上面的error。

**Comment by rickytan** [comment]
```ruby
pod install
```

**Comment by mxpasser** [comment]
@rickytan 刚开始没注意那个pod install提示， 谢谢
