### ISSUE TITLE
RTRootNavigationController怎样右滑返回顶层VC

### ISSUE THREAD

**Issue by easongtd** [rickytan/RTRootNavigationController#30]
RTRootNavigationController针对各别页面怎样右滑返回顶层VC，而不是返回上一级VC？

**Comment by faimin** [comment]
push进新页面后，拿到导航控制器下所有的子控制器，然后把不想要的控制器干掉，这样手势返回时应该就可以直接回到你想要的控制器

**Comment by rickytan** [comment]
👍
