### ISSUE TITLE
设置背景色不起作用，闪一下变回白色

### ISSUE THREAD

**Issue by WangLongONE** [rickytan/RTRootNavigationController#304]
https://user-images.githubusercontent.com/16935224/140700711-8b375d26-e8d4-45c1-94e1-7062925a5cdf.MP4

 self.navigationController.navigationBar.barTintColor = [UIColor blackColor];
在viewDidLoad 里设置的导航栏背景颜色

**Comment by rickytan** [comment]
iOS 15  以上有新的 api ，参考  https://developer.apple.com/documentation/uikit/uinavigationbarappearance?language=objc
