### ISSUE TITLE
iOS 16 使用UIWindowSceneGeometryPreferencesIOS切换横竖屏无效

### ISSUE THREAD

**Issue by mlcldh** [rickytan/RTRootNavigationController#307]
```objc
// 切换横竖屏无效，并且errorHandler也不会回调错误
[viewController setNeedsUpdateOfSupportedInterfaceOrientations];
        UIWindowSceneGeometryPreferencesIOS *geometryPreferences = [[UIWindowSceneGeometryPreferencesIOS alloc] init];
        geometryPreferences.interfaceOrientations = interfaceOrientations;
        [windowScene requestGeometryUpdateWithPreferences:geometryPreferences errorHandler:^(NSError * _Nonnull error) {
            NSLog(@"errorHandler error %@", error);
            if (errorHandler) {
                errorHandler(error);
            }
        }];
```

**Comment by rickytan** [comment]
你的主工程有开启旋转支持吗？我的 demo 测试没问题，虽然回调也没有，但是旋转是生效的
<img width="252" alt="image" src="https://user-images.githubusercontent.com/1250207/196673197-76bae261-e0ec-4593-9307-84240ffd8d9f.png">

**Comment by rickytan** [comment]
关闭设置后，回调有调。
```
Error Domain=UISceneErrorDomain Code=101 "None of the requested orientations are supported by the view controller. Requested: landscapeLeft; Supported: portrait" UserInfo={NSLocalizedDescription=None of the requested orientations are supported by the view controller. Requested: landscapeLeft; Supported: portrait}
```

**Comment by mlcldh** [comment]
> 你的主工程有开启旋转支持吗？我的 demo 测试没问题，虽然回调也没有，但是旋转是生效的 <img alt="image" width="252" src="https://user-images.githubusercontent.com/1250207/196673197-76bae261-e0ec-4593-9307-84240ffd8d9f.png">

打开这个的话，横屏启动App是有问题的。
直接使用UINavigationController的话，只要在AppDelegate里面实现“- (UIInterfaceOrientationMask)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *)window”，就能支持切换横竖屏，而使用RTRootNavigationController就不行。

**Comment by mlcldh** [comment]
@rickytan 我试了下，切换横竖屏无效是我调用的问题，和RTRootNavigationController没关系，不好意思。

**Comment by mlcldh** [comment]
此问题非bug。
