### ISSUE TITLE
无法禁用UIViewController的右滑退出

### ISSUE THREAD

**Issue by easongtd** [rickytan/RTRootNavigationController#31]
我想在某个页面禁止pop右滑退出，设置self.rt_disableInteractivePop = YES;但是不起作用，还是可以右滑，这是什么原因？

**Comment by rickytan** [comment]
`self.rt_disableInteractivePop = YES;` 需要在 viewDidLoad 中设置，之后的更改会无效

**Comment by rickytan** [comment]
will appear 也可以

**Comment by easongtd** [comment]
这个我试过了，原因可能是我自定义了一个BaseNavigationController继承RT，并在里面处理全屏右滑，可能是这个原因导致不能右滑。我后来在BaseNavigationController的gestureRecognizerShouldBegin代理方法中实现了某个页面禁用右滑。
