### ISSUE TITLE
在tabBarController下，第一个分栏的navgationbar需要隐藏，有没有什么好的办法？

### ISSUE THREAD

**Issue by CoderSQ** [rickytan/RTRootNavigationController#34]
<img width="739" alt="2016-12-09 10 32 58" src="https://cloud.githubusercontent.com/assets/19161305/21035598/30638612-bdfb-11e6-95e4-f8a8da3a93bf.png">  这是设置rootvc
<img width="826" alt="2016-12-09 10 34 01" src="https://cloud.githubusercontent.com/assets/19161305/21035599/30684a44-bdfb-11e6-80eb-915f1f395dce.png"> // 这是设置tabbarcontrller的子控制器
<img width="436" alt="2016-12-09 10 34 24" src="https://cloud.githubusercontent.com/assets/19161305/21035600/306cbc6e-bdfb-11e6-9e43-f8456c87d532.png"> 这是设置HTHomeViewController的导航栏隐藏

**Comment by rickytan** [comment]
已经解决了？

**Comment by CoderSQ** [comment]
是的，解决了
