### ISSUE TITLE
self.navigationController.viewControllers 得到的数据总是只有一个。

### ISSUE THREAD

**Issue by wzi90921** [rickytan/RTRootNavigationController#37]
使用了该库之后，
self.navigationController.viewControllers 得到的数组，只有一个数据；
请问，可以通过什么方式，拿到正常的viewcontroller数组呢

**Comment by wzi90921** [comment]
self.rt_navigationController.rt_viewControllers  通过这个就可以得到了

**Comment by rickytan** [comment]
👍
