### ISSUE TITLE
self.navigationController.viewControllers.count 一直为1.

### ISSUE THREAD

**Issue by shaozige** [rickytan/RTRootNavigationController#38]
self.rt_navigationController.viewControllers.count  只能这样写才能正确的获得控制器数组。
没有办法么？项目已经是成型的，想加一下这个导航栏效果。

**Comment by faimin** [comment]
#37

**Comment by rickytan** [comment]
目前的实现，VC 的层级结构是：
```
RTRootNavigationController
    `- RTContainerViewController
    |       `- RTContainerNavigationController
    |               `- YourViewController1
    `- RTContainerViewController
            `- RTContainerNavigationController
                    `- YourViewController2
```
所以，你的 VC `YourViewController` 中访问  **navigationController** 时得到的是上一级 `RTContainerNavigationController`，它只有一个 `childViewControllers` ，就是你自定义的那个。只有通过 `rt_navigationController` 访问才得到顶层的。

解决方法：
1. 如果你的项目 VC 有个共同的基类，可以尝试重写 `- (UINavigationController *)navigationController` 方法；
2. 所有用到 navigationController 的地方都改为 rt_navigationController

**Comment by rickytan** [comment]
如果只是简单的 pop/push ，用 `navigationController` 就可以的

**Comment by heyehao2008** [comment]
可以把这个层级结构写在readme里。很多使用者都会遇到这个使用问题

**Comment by shaozige** [comment]
@rickytan 刚刚发现，self.rt_navigationController.rt_viewControllers 这样写才可以获取到正确的数组，如果单单self.rt_navigationController.viewControllers这样写，是获得不到控制器数组的类的。
确实应该在readme里写个说明，不然不太好弄。

**Comment by shaozige** [comment]
@rickytan  如果我重写- (UINavigationController *)navigationController方法的话，大概思路是怎么样的呢？可以提示一下吗？或者直接code可以吗？谢谢。

**Comment by heyehao2008** [comment]
@shaozige  
```
- (UINavigationController *)navigationController{
    return self.rt_navigationController;
}

**Comment by shaozige** [comment]
@heyehao2008 请问朋友，你这样写可以么？我这样写会white死循环直到报错。错在rtrootviewcontroller中的- (UINavigationController *)rt_navigationController white循环中。

**Comment by heyehao2008** [comment]
@shaozige 我没有这样的需求。一般只有几个viewcontroller需要使用rt_navigationController。
没仔细看源码。不过navigationController应该是被runtime交换了。试试这样重写：
```
- (RTRootNavigationController *)rt_navigationController{
    return self.rt_navigationController;
}
但是这样重写基类后，子类中不能再通过self.rt_navigationController来获取导航控制器了

**Comment by shaozige** [comment]
@heyehao2008 还是实现不了，早知道就先研究源码了，现在开始研究吧。。。

**Comment by rickytan** [comment]
README 已添加
