### ISSUE TITLE
您好! 请问在使用IQKeyboardManager的时候,导致导航栏一起上推,有解决方案么?

### ISSUE THREAD

**Issue by NapoleonBaiAndroid** [rickytan/RTRootNavigationController#4]
主要是没有UIScrollView(UITableView)等滚动视图做根视图的情况下发生

**Comment by rickytan** [comment]
有截图吗？使用系统自带的 `UINavigationController` 会不会？

**Comment by NapoleonBaiAndroid** [comment]
使用系统自带的不会,主要变化就是在UIView做根视图的时候,整个导航栏上推.我怀疑是不是这里面的导航栏是add在view上的?有时间我研究下看看.麻烦你了

**Comment by rickytan** [comment]
![simulator screen shot 2016 6 30 9 46 32](https://cloud.githubusercontent.com/assets/1250207/16474252/cdb361ea-3ea7-11e6-9f4d-6bef134b983b.png)
![simulator screen shot 2016 6 30 9 46 44](https://cloud.githubusercontent.com/assets/1250207/16474253/cdb9a2a8-3ea7-11e6-8234-729137494149.png)

系统的也会啊，没有 `UIScrollView` 的情况下，它只能将整个 `UIWindow` 推上去了

**Comment by NapoleonBaiAndroid** [comment]
好的,O(∩_∩)O谢谢
