### ISSUE TITLE
工程中使用RTRootNavigationController后，在controller中重写- (BOOL)canBecomeFirstResponder 无法调用

### ISSUE THREAD

**Issue by maqihan** [rickytan/RTRootNavigationController#42]
工程中使用RTRootNavigationController后，在controller中重写 - (BOOL)canBecomeFirstResponder ，导致不能调用canBecomeFirstResponder；

**Comment by maqihan** [comment]
我查到 问题出在这里 

__attribute((overloadable)) static inline UIViewController *RTSafeWrapViewController(UIViewController *controller,
                                                                                     Class navigationBarClass,
                                                                                     BOOL withPlaceholder,
                                                                                     UIBarButtonItem *backItem,
                                                                                     NSString *backTitle) {
    if (![controller isKindOfClass:[RTContainerController class]]) {
        return [RTContainerController containerControllerWithController:controller
                                                     navigationBarClass:navigationBarClass
                                              withPlaceholderController:withPlaceholder
                                                      backBarButtonItem:backItem
                                                              backTitle:backTitle];
    }
    return controller;
}

**Comment by rickytan** [comment]
什么情况下会用 VC 的 `- (void)becomeFirstResponder`？

**Comment by xiaoyangh** [comment]
同问，这个问题如何解决？一般的IM软件都会用到这个方法

**Comment by rickytan** [comment]
你是怎么调用的？@xiaoyangh 预期效果是什么？

**Comment by rickytan** [comment]
帮忙试下这个分支 [issue42](https://github.com/rickytan/RTRootNavigationController/tree/issue42) 有没有解决你的问题？

**Comment by PatShen** [comment]
我用融云的SDK验证过，issue42解决了这个问题。

**Comment by Jasonvvei** [comment]
遇到了同样的问题，issue42解决了这个问题
