### ISSUE TITLE
如何在首页隐藏NavigationBar

### ISSUE THREAD

**Issue by ucoker** [rickytan/RTRootNavigationController#43]
- 层级结构

	~~~
	RTRootNavigationController->UITabBarController	-->RTRootNavigationController---》VC1
							-->RTRootNavigationController---》VC2
					  	        -->RTRootNavigationController---》VC3
	~~~

说明：  
第一级`RTRootNavigationController`是为了方便`Routable`来弹出其他`ViewController`，因此需要隐藏  
第二级`UITabBarController`分成三个页面，每一个页面对应自己一个`RTRootNavigationController`。

需求：

- 第一级`RTRootNavigationController`隐藏（首页隐藏NavigationBar）。
- 其他根据需求来决定是否隐藏。

代码：  

- 在`AppDelegate`：
	`- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions`

	```objectivec
	TabBarController *tabbarController = [[TabBarController alloc] init];
	RTRootNavigationController *nav = [[RTRootNavigationController alloc] initWithRootViewController:tabbarController];
	[nav setNavigationBarHidden:YES];
	self.window.rootViewController = nav;
	```

**Comment by ucoker** [comment]
在`TabBarController`添加：  

```objectivec
- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    [self.navigationController setNavigationBarHidden:YES animated:NO];
}
```

可隐藏。

**Comment by rickytan** [comment]
TabbarController 里面的 NavigationController 没必要再用 RootNavigationController，可以用  RTContainerNavigationController ，见 `Demo` 中的  didLaunch 方法

**Comment by ucoker** [comment]
谢谢，看到了。
