### ISSUE TITLE
在执行返回方法的时候如何判断是否为模态视图

### ISSUE THREAD

**Issue by taojeff** [rickytan/RTRootNavigationController#44]
博主，你的返回按钮和滑动返回的时候如何进行判断是否模态视图进入呢？

**Comment by rickytan** [comment]
你是说 `present` 出来的？`present` 时没有返回按钮，滑动返回无效

**Comment by taojeff** [comment]
是的？我昨天准备在集成到框架中的时候突然想到了present这个方式进入页面的时候我看了一下没有这个返回的事件，我原本想在push的返回按钮中增加这个方法，结果还是没有效果。楼主，不知道你有么有什么比较好的办法

**Comment by rickytan** [comment]
在被  `present` 的 **VC** 中设置:
```objective-c
self.navigationItem.leftBarButtonItem = [[UIBarButtonItem alloc] initWithTitle:@"Done" target:self action:@selector(onDone:)];


- (void)onDone:(id)sender
{
  [self dismiss...];
}
```

**Comment by taojeff** [comment]
这个我是知道的在present的页面中进行自定义一个返回按钮来退出，可是我想知道这个时候present的页面如何右滑退出呢？

**Comment by rickytan** [comment]
可以使用自定义转场，但是从下出来，然后又从右返回并不是太友好
