### ISSUE TITLE
rt_disableInteractivePop 被多次设置后无作用

### ISSUE THREAD

**Issue by PatShen** [rickytan/RTRootNavigationController#47]
我在demo的RTWebViewController界面中，添加了一个按钮，事件是每次点击，当前controller的rt_disableInteractivePop置非，
即：self.rt_disableInteractivePop = !self.rt_disableInteractivePop

在执行这个方法前能划出屏幕的情况下，执行之后，依旧能够划出屏幕（正常应该不能再划出了）；
反之亦然；

真实的使用场景例如在 WKWebview 中，设置webview 的allowsBackForwardNavigationGestures 为yes，如果 webivew 的 canGoBack 的值是 YES，此时就不应该触发滑动退出页面的事件，而应该触发webview的goBack事件（类似微信的webview）

根据我的观察，存在以下几种情况
1.在viewDidLoad方法中设置 rt_disableInteractivePop 的值会生效；
2.WKWebview有缓存后，根据webview的状态(是否能goBack)在主线程重新设置rt_disableInteractivePop的值会生效；

**Comment by rickytan** [comment]
这个属性只在  `- (void)viewDidLoad:` 设置一次有效，之后的改变是无效的，就像：
```objective-c
self.extendedLayoutIncludesOpaqueBars;
self.automaticallyAdjustsScrollViewInsets;
self.edgesForExtendedLayout;
```
等属性一样

**Comment by PatShen** [comment]
如果想要在某个ViewController的声明周期中，控制可划出/不可划出，还有其他方式实现吗？

**Comment by rickytan** [comment]
不能一开始就确定吗？如果用户手势返回滑到一半，突然又禁止呢？

**Comment by PatShen** [comment]
是这样子的，iOS8新增的WKWebview，可以通过右滑来返回上一页。
如果一开始确定手势为开启的话，会将WKWebview的右滑手势屏蔽...这里的话我想通过判断WKWebview是否可以返回（canBack）来判断手势是否应该开启。

**Comment by rickytan** [comment]
试试：
```objective-c
self.rt_navigationController.interactivePopGestureRecognizer.enabled = !self.webView.canGoBack;
```
但是记得 vc 消失时还原设置

**Comment by PatShen** [comment]
这个可以！非常感谢！

**Comment by ucoker** [comment]
可行，感谢🙏

**Comment by rickytan** [comment]
使用手势依赖应该更科学点：https://github.com/rickytan/RTRootNavigationController/issues/104#issuecomment-319631950

**Comment by KearLiao** [comment]
![image](https://user-images.githubusercontent.com/10768739/37327474-6e624724-26d1-11e8-9234-f62401d10c61.png)
每次这个都被会设置一次 然后我在viewDidload里面设置 禁止 就失效？

**Comment by rickytan** [comment]
@KearLiao 不会每次都改，还有个条件 `rt_hasSetInteractivePop`
