### ISSUE TITLE
项目中使用了Aspects库然后集成这个库后出现了一些问题

### ISSUE THREAD

**Issue by Jasonvvei** [rickytan/RTRootNavigationController#49]
你好，在项目中原先使用了[Aspects](https://github.com/steipete/Aspects)库替换了UIViewController的viewDidAppear 、viewDidDisappear方法，现在集成了这个库后不能正常的使用，导航栏不能正常的显示，会打印 Unbalanced calls to begin/end appearance transitions for <RTContainerController: 0x7f91b2428400>. 错误信息，有什么解决方法吗?
附件是Demo~
[RTNaviDemo.zip](https://github.com/rickytan/RTRootNavigationController/files/858137/RTNaviDemo.zip)

**Comment by rickytan** [comment]
个人感觉是 Aspects 的 Bug，如下图：
![image](https://cloud.githubusercontent.com/assets/1250207/24185248/14039a9e-0f0d-11e7-88b7-210688fa1ef3.png)
```objective-c
- (void)viewDidAppear:
```
会进两次。同时，push 到新的 **VC** 时，无缘无故地 disappear 了两次，去掉 aspects 相关代码后正常。

另外，当 aspects 注入的方法被  swizzle 过后，运行会 crash，可能是同一个 bug 引起的，如这样：
```objective-c
@interface UIViewController (P)
@end

@implementation UIViewController (P)

+ (void)load
{
    method_exchangeImplementations(class_getInstanceMethod(self, @selector(viewDidAppear:)),
                                   class_getInstanceMethod(self, @selector(p_viewDidAppear:)));
}

- (void)p_viewDidAppear:(BOOL)animated
{
    [self p_viewDidAppear:animated];
}

@end
```

**Comment by Jasonvvei** [comment]
好的，感谢解答。准备把Aspects给拿掉了，然后自己swizzle，的确是有些问题。
