### ISSUE TITLE
如何修改rootvc的导航栏颜色

### ISSUE THREAD

**Issue by huangxianhui001** [rickytan/RTRootNavigationController#5]
下载你的Demo,注释掉appdelegate的代码,使用包含tabbarController的例子,然后发现Root那个tabbar的根控制器是RTStaticTableViewController,我想要修改这个控制器的导航栏背景色,或者自定义导航栏样式,在该.m文件中添加rt_navigationBarClass这个方法,返回一个自定义UINavigationBar类,但是没有效果,请问,在这种情况下,如何修改根控制器的导航栏背景?

**Comment by rickytan** [comment]
像以前一样就好了：
```objc
[self.navigationController.navigationBar setBarTintColor:xxx]
```

**Comment by huangxianhui001** [comment]
还是不行啊,比如在RTPushRemoveViewController里面添加一个touchesBegan:withEvent:,方法在触摸开始时,push一个新的RTPushRemoveViewController对象进来,然后我在这个控制器的viewwillAppear方法修改:[self.navigationController.navigationBar setBarTintColor:[UIColor blueColor]],在新push的这个页面,颜色就有改,但是作为RTContainerNavigationController根控制器的那个页面,位于栈底的那个控制器,就是没法改

**Comment by rickytan** [comment]
已修复，感谢反馈（应该是 fix #5 ，打错了）：[61f877a](https://github.com/rickytan/RTRootNavigationController/commit/61f877aa3ab54e4e4e99be06b135e3258fc98121)
