### ISSUE TITLE
[self.rt_navigationController removeViewController:obj] 不起作用

### ISSUE THREAD

**Issue by immustard** [rickytan/RTRootNavigationController#53]
这个方法不起作用，是我用的方式不对么。

**Comment by rickytan** [comment]
你的层级结构是怎样的？obj 最好是一个目前不可见 vc

**Comment by iTiny** [comment]
我也遇见同样问题。
断点发现，for循环每次取到的rt_nav.viewControllers的指针都不一样，移除都是无效的~

**Comment by rickytan** [comment]
您试试 `self.rt_navigationController.rt_viewControllers` 呢？这个注释中有提到的 <https://github.com/rickytan/RTRootNavigationController/blob/master/RTRootNavigationController/Classes/RTRootNavigationController.h#L79>

**Comment by jiqiuyucool** [comment]
NSMutableArray *marr = [[NSMutableArray alloc]initWithArray:self.rt_navigationController.rt_viewControllers];
        for (UIViewController *vc in marr) {
            
          
            if ([vc isKindOfClass:[MCAddNewOrderVC class]]) {
                [marr removeObject:vc];
                NSLog(@"delect%@",vc);
                break;
            }
        }
    self.rt_navigationController.rt_viewControllers = marr;
    
     NSMutableArray *marr2 = [[NSMutableArray alloc]initWithArray:self.rt_navigationController.rt_viewControllers];
    
    for (UIViewController *vc in marr2) {
        
        NSLog(@"+++%@",vc);
    }

移除无效~~~~

**Comment by rickytan** [comment]
试试：
```objective-c
[self.rt_navigationController removeViewController:xxx];
```
