### ISSUE TITLE
请问这种控制器结构下  该如何监听系统侧滑返回

### ISSUE THREAD

**Issue by jianmu297** [rickytan/RTRootNavigationController#55]
如题

**Comment by rickytan** [comment]
监听是指开始手势返回时收到回调？

**Comment by jianmu297** [comment]
确认侧滑成功后返回上一页面时，可能需要处理一些业务逻辑

**Comment by rickytan** [comment]
意思是点返回按钮返回与手势返回逻辑会不一样对吧？

**Comment by jianmu297** [comment]
点返回按钮返回，可以直接在返回事件中处理业务逻辑 ，但是手势返回完成不知道如何监听。两者处理的业务逻辑基本一致，分开一起处理都行。。主要是如何监听这个侧滑完成。。。。

**Comment by rickytan** [comment]
如果是点击返回的话，您是怎么处理的？给个示例代码

**Comment by jianmu297** [comment]
参照readme，直接在控制器基类重写customBackItemWithTarget 
`
- (UIBarButtonItem *)customBackItemWithTarget:(id)target action:(SEL)action{
    
    UIButton *backButton = [UIButton buttonWithType:UIButtonTypeCustom];
    [backButton setTitle:@"" forState:UIControlStateNormal];
    [backButton setImage:[UIImage imageNamed:@"customBackImage"] forState:UIControlStateNormal];
    [backButton setImage:[UIImage imageNamed:@"customBackImage"] forState:UIControlStateHighlighted];
    [backButton addTarget:self action:@selector(popBack) forControlEvents:UIControlEventTouchUpInside];

    [backButton sizeToFit];
    backButton.contentEdgeInsets = UIEdgeInsetsMake(0, 0, 0, 0);
    
    return  [[UIBarButtonItem alloc] initWithCustomView:backButton];
}

- (void)popBack{
    
     NSLog(@"pop");
    [self.rt_navigationController popViewControllerAnimated:YES];

}
`

**Comment by rickytan** [comment]
如果只是当前这个 VC 需要回调的话，可以尝试 UINavigationControllerDelegate

```objective-c
- (void)viewDidLoad
{
   [super viewDidLoad];
   self.rt_navigationController.delegate = self;
   ...
}

- (id <UIViewControllerAnimatedTransitioning>)navigationController:(UINavigationController *)navigationController
                                   animationControllerForOperation:(UINavigationControllerOperation)operation
                                                fromViewController:(UIViewController *)fromVC
                                                  toViewController:(UIViewController *)toVC
{
   if (fromVC == self && operation == UINavigationControllerOperationPop）{
      // 你的代码
   }
}
```

**Comment by rickytan** [comment]
更简单的方式：
```objective-c
- (void)viewWillDisappear:(BOOL)animated
{
    if (self.isMovingFromParentViewController) {
        // 你的代码
    }
}
```
