### ISSUE TITLE
如何pop到指定的控制器

### ISSUE THREAD

**Issue by GosyHuang** [rickytan/RTRootNavigationController#63]

**Comment by rickytan** [comment]
跟普通的 `UINavigationController` 一样的：
```objective-c
- (void)popToViewController:(UIViewController *)vc animated:(BOOL)animated
```

**Comment by Hearsayer** [comment]
如果，从A到B到C，A->B->C，现在要从C退回到A，好像无法使用```- (void)popToViewController:(UIViewController *)vc animated:(BOOL)animated```这个方法，每个导航控制只能拿到，当前的控制器，无法拿到之前的控制器
