### ISSUE TITLE
自定义按钮无法点击返回

### ISSUE THREAD

**Issue by taojeff** [rickytan/RTRootNavigationController#67]
博主，我在用你的项目功能代码集成到我的项目后可以实现滑动返回 可是这个时候我的自定义返回按钮则没法点击使用了

**Comment by taojeff** [comment]
我不论在返回页面使用rt_disableInteractivePop为NO或者YES都不行

**Comment by rickytan** [comment]
您的实现代码能不能贴一下，就是那个 `- (UIBarButtonItem *)customBackBarButton...`

**Comment by taojeff** [comment]
是我这边的问题 我没有把原来的代码给删除 所以导致覆盖到你的返回按钮上了
