### ISSUE TITLE
setBackgroundImage方法的一些问题

### ISSUE THREAD

**Issue by Jasonvvei** [rickytan/RTRootNavigationController#71]
你好，发现如果设置了  [navigationBar setBackgroundImage]  的话，view的开始位置不是从0开始的，而是从导航栏下面开始的，但是使用系统的NavigationController并不会出现这个问题，具体效果可以看下Demo，请问可以设置和系统的一样吗?
[Demo0506.zip](https://github.com/rickytan/RTRootNavigationController/files/980650/Demo0506.zip)

**Comment by rickytan** [comment]
您可以在你的 VC `- init`，或 `- viewDidLoad` 中设置：
```objective-c
        self.edgesForExtendedLayout = UIRectEdgeAll;
        self.automaticallyAdjustsScrollViewInsets = NO;
        self.extendedLayoutIncludesOpaqueBars = YES;
```

**Comment by rickytan** [comment]
这个问题在于，你之前的  **VC3**，只设置了 `barTintColor = [UIColor cyanColor]`，所有 **navigationBar** 其实是透明的，而系统自带的是共用 **navigationBar** 的，到 **VC4** 时还是透明的，所有从 0 开始。
本项目到 **VC4** 时，是一个新的 **navigationBar**，同时你设置了一个没有透明区的 image 作为背景，所有 **navigationBar** 变为不透明了，所有 **VC4** 是从导致条下面开始，行为本身没有错误的
