### ISSUE TITLE
Appdelegate中获取当前视图始终是RTContainerController,有办法改变吗

### ISSUE THREAD

**Issue by vistaLin** [rickytan/RTRootNavigationController#74]
UIViewController *tempVC = [UIApplication sharedApplication].keyWindow.rootViewController;
    while (1) {
        if ([tempVC isKindOfClass:[UITabBarController class]]) {
            tempVC = ((UITabBarController *)tempVC).selectedViewController;
           
        }
        if ([tempVC isKindOfClass:[UINavigationController class]]) {
            tempVC = ((UINavigationController *)tempVC).visibleViewController;
        }
        if (tempVC.presentedViewController) {
            tempVC = tempVC.presentedViewController;
            
        } else {
            break;
        }
    }
获取不到当前视图了,都是获取到RTContainerController了

**Comment by rickytan** [comment]
您的 VC 层级结构是怎样的？如果 `rootViewController` 是 **RTRootNavigationController** ，你可以访问 `rootViewController.rt_visiableViewController` 或者 `rootViewController.rt_topViewController` ，见注释文档：<https://github.com/rickytan/RTRootNavigationController/blob/master/RTRootNavigationController/Classes/RTRootNavigationController.h#L76>

**Comment by vistaLin** [comment]
谢谢,开始没详细看.....
