### ISSUE TITLE
转场动画问题

### ISSUE THREAD

**Issue by justForL** [rickytan/RTRootNavigationController#75]
自定义转场动画,做pop操作,点击返回按钮可以进入到代理中识别到pop操作,但是利用手势返回,就无法进入代理,请问有什么好的办法解决么?push操作没有这个问题

**Comment by rickytan** [comment]
这是个问题。刚才用系统自带用 `UINavigationController` 测试发现，当设置了 delegate 时无法手势返回，有效规避了这个问题
