### ISSUE TITLE
根控制器无法自定义statusBar颜色

### ISSUE THREAD

**Issue by huangxianhui001** [rickytan/RTRootNavigationController#8]
也是使用tabbarController的例子,在根控制器的.m文件里修改statusbar的样式,没有效果,然后push到一个新的控制器进来,就可以修改了

**Comment by rickytan** [comment]
这个，你得自己继承 `UITabBarController` ，然后，将 ·preferedStatusBarStyle· 转发到 ·selectedViewController· 上

**Comment by huangxianhui001** [comment]
恩,我已经解决了,就是用这个方法
