### ISSUE TITLE
设置 navigationBar setBackgroundImage背景图片 不起作用

### ISSUE THREAD

**Issue by pickView** [rickytan/RTRootNavigationController#80]
BaseNavController : RTRootNavigationController 
//设置背景图片 失败
navigationBar setBackgroundImage
//换个思路 设置导航栏颜色 失败
navigationBar.barTintColor = DGJMainColor(0, 222, 168);
是我哪一步有问题吗？请指正，谢谢，期待您的回复。

**Comment by pickView** [comment]
看了一下已解决的问题，RTRootNavigationController是让每个vc管理自己的navigationBar，所以，直接设置NavigationController 并不会发生作用。

**Comment by rickytan** [comment]
对，应用场景不一样。不过您也可以通过  `appearance` 全局设置：
```objective-c
[[UINavigationBar appearance] setBackgroundImage:...];
```

**Comment by rickytan** [comment]
或者设置 `transferNavigationBarAttributes` 为 **YES**
