### ISSUE TITLE
navigationBar下面的线条怎么全局去除呢

### ISSUE THREAD

**Issue by RideShi** [rickytan/RTRootNavigationController#81]

**Comment by RideShi** [comment]
并且 self.rt_navigationController.interactivePopGestureRecognizer.enabled = NO;  在某一页面设置后，滑动还是存在

**Comment by pickView** [comment]
//取消导航栏线条
    UINavigationBar *navigationBar = self.navigationBar;
    [navigationBar setBackgroundImage:[[UIImage alloc] init]
                       forBarPosition:UIBarPositionAny
                           barMetrics:UIBarMetricsDefault];
    [navigationBar setShadowImage:[UIImage new]];    //设置RTNavi全局
    [self.navigationBar setTintColor:[UIColor whiteColor]];

**Comment by RideShi** [comment]
已经写好了，但还是谢谢指导🙏
