### ISSUE TITLE
tabbar隐藏的问题

### ISSUE THREAD

**Issue by SimleCp** [rickytan/RTRootNavigationController#84]
原来都是自己继承系统的导航栏控制器做的.在这个方法里面隐藏非根控制器的tabbar, 请问一下现在应该如何隐藏?
```
- (void)pushViewController:(UIViewController *)viewController animated:(BOOL)animated
{
    if (self.viewControllers.count != 0) {
        viewController.hidesBottomBarWhenPushed = YES;
    }
    [super pushViewController:viewController animated:animated];
}
```

**Comment by rickytan** [comment]
这个实现可以的呀，不行么？

**Comment by SimleCp** [comment]
我的意思是说, 用你的框架, 我应该如何实现这个需求....因为你的框架自己也加了几个push方法,  我如果直接给这个方法- (void)pushViewController:(UIViewController *)viewController animated:(BOOL)animated添加, 假如用你加的push方法, 会不会出现无法隐藏底部栏的问题?

**Comment by rickytan** [comment]
最好的实现是这样，参考 https://github.com/rickytan/RTRootNavigationController/blob/master/Example/RTRootNavigationController/RTAppDelegate.m#L25-L29
只在 root 保留 tabBar

**Comment by SimleCp** [comment]
弄好了. 谢谢    ^ . ^
