### ISSUE TITLE
会出现个别界面，首次侧滑返回会卡顿

### ISSUE THREAD

**Issue by RideShi** [rickytan/RTRootNavigationController#85]

**Comment by rickytan** [comment]
你的上级 VC 的 `-viewWillAppear` 或者当前 VC 的 `-viewWillDisappear` 有没有什么很重的操作？

**Comment by RideShi** [comment]
没有，偶现，有些界面的-viewwillappear和viewwilldisappear方法都没重写

**Comment by rickytan** [comment]
原因在阴影了：https://github.com/rickytan/RTRootNavigationController/issues/83#issuecomment-308615068

**Comment by RideShi** [comment]
嗯。在试了

**Comment by RideShi** [comment]
卡顿是因为地图和手势

**Comment by YogaChen** [comment]
@RideShi 请问在地图的页面侧滑返回卡顿的问题是怎么解决的，代码怎么设置，还以为是地图的问题呢
