### ISSUE TITLE
self.navigationController.navigationBar.barStyle = UIBarStyleDefault; 不起作用了

### ISSUE THREAD

**Issue by maqihan** [rickytan/RTRootNavigationController#9]
self.navigationController.navigationBar.barStyle = UIBarStyleDefault; 不起作用了，在系统的navgationcoller下设置是起作用的，但是在RTRootNavigationController下的viewcontroller中设置不起作用。只能通过preferredStatusBarStyle 改变状态栏颜色。不知道是不是bug？

**Comment by rickytan** [comment]
系统的 `UINavigationController` 起作用时，有没有设置：
![2016-07-06 9 29 24](https://cloud.githubusercontent.com/assets/1250207/16604844/2bb91f6a-435c-11e6-9796-d7419ef5564f.png)
为 **YES** ？

**Comment by maqihan** [comment]
在info.plist已经做了设置。我觉得设置这个对于self.navigationController.navigationBar.barStyle起不起作用没关系。我在您的demo中也做了测试发现也不起作用 self.navigationController.navigationBar.barStyle = UIBarStyleDefault;但是这句话在系统navigationController下设置是起作用的。还没具体看demo中的实现代码，暂时不清楚咋回事？

**Comment by rickytan** [comment]
大概知道了，系统的 `UINavigationController` 当 navigationBar 可见时，会接管 status style ，当 navigationBar 为 **Default**，为 黑色，其他为白色；当 navigationBar 不可见时，会转发到当前可见的 view controller 上。你可以试试。

在本项目的实现下还是都转发到当前 view controller 好些
