### ISSUE TITLE
不显示角标

### ISSUE THREAD

**Issue by weizhangCoder** [rickytan/RTRootNavigationController#91]
正常的UINavgation设置角标展示  [self.navigationController.tabBarItem setBadgeValue:@"5"];
继承RTRoot的角标不展示。这是什么原因

**Comment by rickytan** [comment]
直接  `self.tabBarItem` 试试？

**Comment by weizhangCoder** [comment]
我重新弄个工程好像没有问题了，可能别的代码影响的
