### ISSUE TITLE
重写RTContainerNavigationController中 Viewcontrollers get方法来避免Notice中的另类调用

### ISSUE THREAD

**Issue by leavesster** [rickytan/RTRootNavigationController#92]
根据Notice的描述，那意味着如果使用RTRootNavigationController，以前所有用到该方法的地方，都需要更改。
而且这个更改还不会有警告，虽然可以使用正则查找之类的办法替换，但是总觉得不是个好方法。

我想到的一种办法是重写`RTContainerNavigationController`中 `Viewcontrollers` `get`方法，具体代码如下：

```
- (NSArray *)viewControllers
{
    if (self.navigationController) {
        if ([self.navigationController isKindOfClass:[RTRootNavigationController class]]) {
            return self.rt_navigationController.rt_viewControllers;
        }
    }
    return [super viewControllers];
}
```

这样应该可以做到尽量少的侵入性。
不知道这种办法是不是有什么不好的地方，导致您没用？
毕竟我只看了一部分源码。谢谢。

**Comment by leavesster** [comment]
如果您觉得可行，没时间改，我也可以提个PR。
如果不可行，能够给告知下，可能会有什么问题？

**Comment by rickytan** [comment]
貌似是可以的。
我之前试过直接覆盖 RTRootNavigationController 的 viewControllers 方法，会导致问题，因为它内部会使用这个，且默认情况下，它认为这个数组中的所有成员都是它的子 **VC**，而事实上越了一层父子关系。但是这个好像没问题，你可以提 PR

**Comment by leavesster** [comment]
刚好您push了两个commit，我是这之前fork的，然后合并了一次更新。
似乎合并的commit导致了Travis CI 运行失败，我的PR只是单纯增加了上面的代码，没有其他改动。

**Comment by rickytan** [comment]
这个没问题的，我有空再验证下各种可能的使用情况
