### ISSUE TITLE
手势默认不支持侧滑

### ISSUE THREAD

**Issue by jifengchao** [rickytan/RTRootNavigationController#96]
版本更新到0.6.1后发现，手势默认不支持侧滑了

**Comment by jifengchao** [comment]
发现是因为自定义了返回Item，还有就是，在-viewDidLoad里，设置rt_disableInteractivePop = YES，依然可以手势侧滑

**Comment by rickytan** [comment]
对，ChangeLog 中已经说明了，特地升了 minor 版本号，防止自动更新到这个

**Comment by rickytan** [comment]
自定义返回 item ，您可以重写  `-rt_customBackItemWithTarget:action:` 方法，不用设置 `leftBarButtonItem`

**Comment by mTerminal** [comment]
@rickytan 尝试重写-rt_customBackItemWithTarget:action:方法，并没有生效，只能暂时退到0.5版本使用。

**Comment by rickytan** [comment]
重写这个，同时不能手动设置 `self.navigationItem.leftBarButtonItem` 了，检查下代码？

**Comment by mTerminal** [comment]
@rickytan 我找到问题了，需要useSystemBackBarButtonItem设置为false，而他默认是false，我从没对这个属性做过操作，不知道原因在哪里，手动设置为false可以正常修改了。

**Comment by rickytan** [comment]
这个值应该不会影响返回按钮的，如果真有影响，那是个 bug

**Comment by mTerminal** [comment]
观察源码，发现useSystemBackBarButtonItem确实会影响-rt_customBackItemWithTarget:action:的执行。[rtroot](http://orw4ygcvy.bkt.clouddn.com/rtroot.png)

**Comment by rickytan** [comment]
是个问题！感谢反馈
