### ISSUE TITLE
指定页面不能取消侧滑手势?

### ISSUE THREAD

**Issue by leoxpx** [rickytan/RTRootNavigationController#97]
在某个页面中通过属性设置
self.rt_navigationController.rt_disableInteractivePop = YES;
不起作用. 不能用吗?

**Comment by leoxpx** [comment]
已解决self.rt_disableInteractivePop = YES;

**Comment by developer-poplar** [comment]
> self.rt_disableInteractivePop = YES;
非常感谢，我也遇到了同样的问题
