### ISSUE TITLE
存在内存泄漏风险

### ISSUE THREAD

**Issue by lly4155** [rickytan/RTRootNavigationController#98]
无论在模拟器还是真机上，pop后内存只增不减

**Comment by rickytan** [comment]
已经进行一年多了，内存检测工具也有检测出不少泄漏问题，但是由这个产生的貌似还没有。你改为系统的导航器确定是没问题的吗？

**Comment by lly4155** [comment]
我用leaks工具检测pop没有提示泄漏，但是内存一直没降低，改为系统的测试了下发现内存也没释放，但是增长速度要慢些，一时间没有搞懂原理。

**Comment by rickytan** [comment]
内存使用增长快些是正常的，因为层级比自带的导航多了。你可以手动触发内存警告，看会不会下降，模拟器中按：
![image](https://user-images.githubusercontent.com/1250207/28346370-3f3fe5b0-6c63-11e7-89fc-9c0f9a35f369.png)

**Comment by lly4155** [comment]
手动触发内存警告后pop会降低，但是降低的比升高的少，这代表什么呢

**Comment by jianmu297** [comment]
我这边是pop后不走dealloc？  不是很懂。。。

**Comment by rickytan** [comment]
代表可能有创建不少单例，无法释放，全局变量等，或者就是其他地方有引用循环

**Comment by lly4155** [comment]
如果有引用循环的话，用leak检查应该会提示个错误吧？

**Comment by rickytan** [comment]
会有警告，如：
![image](https://user-images.githubusercontent.com/1250207/28505895-fcde9162-7059-11e7-9ec4-6e06962ac41f.png)

**Comment by lly4155** [comment]
这个溢出倒没有

**Comment by lly4155** [comment]
看起来一切都很正常。。没有任何警告

**Comment by cao903775389** [comment]
确实存在控制器无法释放的情况 在pop后deinit方法没有调用

**Comment by cao903775389** [comment]
老版本的没有这个问题  0.5.26 能够正常释放

**Comment by rickytan** [comment]
dealloc 吧，哪有 deinit 。是部分控制器，还是所有？

**Comment by cao903775389** [comment]
不好意思啦 是我这边的问题 现在可以正常释放了 deinit是swift里的
